// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Acid_INCLUDED
#define _EntitiesV_Acid_INCLUDED 1
#define EVENTCODE_EAcid 0x01fd0000
class DECL_DLL EAcid : public CEntityEvent {
public:
EAcid();
CEntityEvent *MakeCopy(void);
CEntityPointer penOwner;
CEntityPointer penTarget;
};
DECL_DLL inline void ClearToDefault(EAcid &e) { e = EAcid(); } ;
extern "C" DECL_DLL CDLLEntityClass CAcid_DLLClass;
class CAcid : public CMovableModelEntity {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  CEntityPointer m_penOwner;
  CEntityPointer m_penTarget;
  BOOL m_bLoop;
#define  STATE_CAcid_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x01fd0001_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01fd0002_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x01fd0003_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x01fd0004_Main_04(const CEntityEvent &__eeInput);
};

static const char *CAcid_propnames[] = {
  "m_penOwner",
  "m_penTarget",
  "m_bLoop",
};
#define CAcid_propnamesct ARRAYCOUNT(CAcid_propnames)

#endif // _EntitiesV_Acid_INCLUDED
