// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#define ENTITYCLASS CAcid

CEntityProperty CAcid_properties[] = {
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000001fd<<8)+1, offsetof(CAcid, m_penOwner), "", 0, "m_penOwner", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000001fd<<8)+2, offsetof(CAcid, m_penTarget), "", 0, "m_penTarget", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x000001fd<<8)+5, offsetof(CAcid, m_bLoop), "", 0, "m_bLoop", 0, 0),
};
#define CAcid_propertiesct ARRAYCOUNT(CAcid_properties)

CEntityComponent CAcid_components[] = {
  CEntityComponent()
};
#define CAcid_componentsct 0


CEventHandlerEntry CAcid_handlers[] = {
 {1, -1, CEntity::pEventHandler(&CAcid::Main),DEBUGSTRING("CAcid::Main")},
 {0x01fd0001, -1, CEntity::pEventHandler(&CAcid::H0x01fd0001_Main_01), DEBUGSTRING("CAcid::H0x01fd0001_Main_01")},
 {0x01fd0002, -1, CEntity::pEventHandler(&CAcid::H0x01fd0002_Main_02), DEBUGSTRING("CAcid::H0x01fd0002_Main_02")},
 {0x01fd0003, -1, CEntity::pEventHandler(&CAcid::H0x01fd0003_Main_03), DEBUGSTRING("CAcid::H0x01fd0003_Main_03")},
 {0x01fd0004, -1, CEntity::pEventHandler(&CAcid::H0x01fd0004_Main_04), DEBUGSTRING("CAcid::H0x01fd0004_Main_04")},
};
#define CAcid_handlersct ARRAYCOUNT(CAcid_handlers)

CEntity *CAcid_New(void) { return new CAcid; };
void CAcid_OnInitClass(void) {};
void CAcid_OnEndClass(void) {};
void CAcid_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CAcid_OnWorldEnd(CWorld *pwo) {};
void CAcid_OnWorldInit(CWorld *pwo) {};
void CAcid_OnWorldTick(CWorld *pwo) {};
void CAcid_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CAcid, CMovableModelEntity, "Acid", "", 0x000001fd);
DECLARE_CTFILENAME(_fnmCAcid_tbn, "");
