// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_AirWave_INCLUDED
#define _EntitiesV_AirWave_INCLUDED 1
#define EVENTCODE_EAirWave 0x01fe0000
class DECL_DLL EAirWave : public CEntityEvent {
public:
EAirWave();
CEntityEvent *MakeCopy(void);
CEntityPointer penLauncher;
};
DECL_DLL inline void ClearToDefault(EAirWave &e) { e = EAirWave(); } ;
extern "C" DECL_DLL CDLLEntityClass CAirWave_DLLClass;
class CAirWave : public CMovableModelEntity {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  CEntityPointer m_penLauncher;
  FLOAT m_fDamageAmount;
  FLOAT m_fIgnoreTime;
  FLOAT m_fStartTime;
   void PreMoving(void);
   BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   void AirWaveTouch(CEntityPointer penHit);
#define  STATE_CAirWave_AirWaveSlide 0x01fe0001
  BOOL AirWaveSlide(const CEntityEvent &__eeInput);
  BOOL H0x01fe0002_AirWaveSlide_01(const CEntityEvent &__eeInput);
  BOOL H0x01fe0003_AirWaveSlide_02(const CEntityEvent &__eeInput);
#define  STATE_CAirWave_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x01fe0004_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01fe0005_Main_02(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_AirWave_INCLUDED
