// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#define ENTITYCLASS CBouncer

CEntityProperty CBouncer_properties[] = {
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_STRING, NULL, (0x00000069<<8)+1, offsetof(CBouncer, m_strName), "Name", 'N', "m_strName", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_STRING, NULL, (0x00000069<<8)+2, offsetof(CBouncer, m_strDescription), "", 0, "m_strDescription", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000069<<8)+4, offsetof(CBouncer, m_fSpeed), "Speed [m/s]", 'S', "m_fSpeed", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ANGLE3D, NULL, (0x00000069<<8)+5, offsetof(CBouncer, m_aDirection), "Direction", 'D', "m_aDirection", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000069<<8)+6, offsetof(CBouncer, m_tmControl), "Control time", 'T', "m_tmControl", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x00000069<<8)+7, offsetof(CBouncer, m_bEntrySpeed), "", 0, "m_bEntrySpeed", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000069<<8)+10, offsetof(CBouncer, m_fMaxExitSpeed), "Max exit speed", 'M', "m_fMaxExitSpeed", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000069<<8)+12, offsetof(CBouncer, m_fNormalComponentMultiplier), "Normal component multiplier", 'O', "m_fNormalComponentMultiplier", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000069<<8)+13, offsetof(CBouncer, m_fParallelComponentMultiplier), "Parallel component multiplier", 'P', "m_fParallelComponentMultiplier", 0x7F0000FFUL, 0),
};
#define CBouncer_propertiesct ARRAYCOUNT(CBouncer_properties)

CEntityComponent CBouncer_components[] = {
  CEntityComponent()
};
#define CBouncer_componentsct 0


CEventHandlerEntry CBouncer_handlers[] = {
 {1, -1, CEntity::pEventHandler(&CBouncer::Main),DEBUGSTRING("CBouncer::Main")},
};
#define CBouncer_handlersct ARRAYCOUNT(CBouncer_handlers)

CEntity *CBouncer_New(void) { return new CBouncer; };
void CBouncer_OnInitClass(void) {};
void CBouncer_OnEndClass(void) {};
void CBouncer_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CBouncer_OnWorldEnd(CWorld *pwo) {};
void CBouncer_OnWorldInit(CWorld *pwo) {};
void CBouncer_OnWorldTick(CWorld *pwo) {};
void CBouncer_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CBouncer, CRationalEntity, "Bouncer", "Thumbnails\\Bouncer.tbn", 0x00000069);
DECLARE_CTFILENAME(_fnmCBouncer_tbn, "Thumbnails\\Bouncer.tbn");
