// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#define ENTITYCLASS CEnemyMarker

CEntityProperty CEnemyMarker_properties[] = {
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x0000012e<<8)+1, offsetof(CEnemyMarker, m_fWaitTime), "", 0, "m_fWaitTime", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_RANGE, NULL, (0x0000012e<<8)+3, offsetof(CEnemyMarker, m_fMarkerRange), "Marker Range", 'M', "m_fMarkerRange", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_RANGE, NULL, (0x0000012e<<8)+11, offsetof(CEnemyMarker, m_fPatrolAreaInner), "Patrol Area Inner", 'R', "m_fPatrolAreaInner", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_RANGE, NULL, (0x0000012e<<8)+12, offsetof(CEnemyMarker, m_fPatrolAreaOuter), "Patrol Area Outer", 'E', "m_fPatrolAreaOuter", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x0000012e<<8)+13, offsetof(CEnemyMarker, m_fPatrolTime), "Patrol Time", 'P', "m_fPatrolTime", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENUM, &BoolEType_enum, (0x0000012e<<8)+14, offsetof(CEnemyMarker, m_betRunToMarker), "Run to marker", 'O', "m_betRunToMarker", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENUM, &BoolEType_enum, (0x0000012e<<8)+15, offsetof(CEnemyMarker, m_betFly), "Fly", 'F', "m_betFly", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENUM, &BoolEType_enum, (0x0000012e<<8)+16, offsetof(CEnemyMarker, m_betBlind), "Blind", 'B', "m_betBlind", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENUM, &BoolEType_enum, (0x0000012e<<8)+17, offsetof(CEnemyMarker, m_betDeaf), "Deaf", 'D', "m_betDeaf", 0x7F0000FFUL, 0),
};
#define CEnemyMarker_propertiesct ARRAYCOUNT(CEnemyMarker_properties)

CEntityComponent CEnemyMarker_components[] = {
#define MODEL_MARKER ((0x0000012e<<8)+1)
 CEntityComponent(ECT_MODEL, MODEL_MARKER, "EFNM" "Models\\Editor\\EnemyMarker.mdl"),
#define TEXTURE_MARKER ((0x0000012e<<8)+2)
 CEntityComponent(ECT_TEXTURE, TEXTURE_MARKER, "EFNM" "Models\\Editor\\EnemyMarker.tex"),
};
#define CEnemyMarker_componentsct ARRAYCOUNT(CEnemyMarker_components)

CEventHandlerEntry CEnemyMarker_handlers[] = {
 {1, -1, CEntity::pEventHandler(&CEnemyMarker::Main),DEBUGSTRING("CEnemyMarker::Main")},
};
#define CEnemyMarker_handlersct ARRAYCOUNT(CEnemyMarker_handlers)

CEntity *CEnemyMarker_New(void) { return new CEnemyMarker; };
void CEnemyMarker_OnInitClass(void) {};
void CEnemyMarker_OnEndClass(void) {};
void CEnemyMarker_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CEnemyMarker_OnWorldEnd(CWorld *pwo) {};
void CEnemyMarker_OnWorldInit(CWorld *pwo) {};
void CEnemyMarker_OnWorldTick(CWorld *pwo) {};
void CEnemyMarker_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CEnemyMarker, CMarker, "Enemy Marker", "Thumbnails\\EnemyMarker.tbn", 0x0000012e);
DECLARE_CTFILENAME(_fnmCEnemyMarker_tbn, "Thumbnails\\EnemyMarker.tbn");
