// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_EnemyRunInto_INCLUDED
#define _EntitiesV_EnemyRunInto_INCLUDED 1
#include <EntitiesV/EnemyBase.h>
extern "C" DECL_DLL CDLLEntityClass CEnemyRunInto_DLLClass;
class DECL_DLL  CEnemyRunInto : public CEnemyBase {
public:
   virtual void SetDefaultProperties(void);
  CEntityPointer m_penLastTouched;
  FLOAT m_fLastTouchedTime;
  BOOL m_bWhileLoop;
  FLOAT m_fMassKicked;
  ANGLE m_fAttackRotateRunInto;
  virtual void AdjustDifficulty(void);
   void IncreaseKickedMass(CEntity * pen);
  virtual void LiveEntityTouched(ETouch etouch);
  virtual BOOL HigherMass(void);
#define  STATE_CEnemyRunInto_Fire 0x01380000
  BOOL Fire(const CEntityEvent &__eeInput);
#define  STATE_CEnemyRunInto_RotateToEnemy 0x01380001
  BOOL RotateToEnemy(const CEntityEvent &__eeInput);
  BOOL H0x01380002_RotateToEnemy_01(const CEntityEvent &__eeInput);
  BOOL H0x01380003_RotateToEnemy_02(const CEntityEvent &__eeInput);
  BOOL H0x01380004_RotateToEnemy_03(const CEntityEvent &__eeInput);
  BOOL H0x01380005_RotateToEnemy_04(const CEntityEvent &__eeInput);
#define  STATE_CEnemyRunInto_RunIntoEnemy 0x01380006
  BOOL RunIntoEnemy(const CEntityEvent &__eeInput);
  BOOL H0x01380007_RunIntoEnemy_01(const CEntityEvent &__eeInput);
  BOOL H0x01380008_RunIntoEnemy_02(const CEntityEvent &__eeInput);
  BOOL H0x01380009_RunIntoEnemy_03(const CEntityEvent &__eeInput);
  BOOL H0x0138000a_RunIntoEnemy_04(const CEntityEvent &__eeInput);
#define  STATE_CEnemyRunInto_RunAwayFromEnemy 0x0138000b
  BOOL RunAwayFromEnemy(const CEntityEvent &__eeInput);
  BOOL H0x0138000c_RunAwayFromEnemy_01(const CEntityEvent &__eeInput);
  BOOL H0x0138000d_RunAwayFromEnemy_02(const CEntityEvent &__eeInput);
#define  STATE_CEnemyRunInto_MainLoop 0x0138000e
  BOOL MainLoop(const CEntityEvent &__eeInput);
#define  STATE_CEnemyRunInto_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_EnemyRunInto_INCLUDED
