// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_EnvironmentBase_INCLUDED
#define _EntitiesV_EnvironmentBase_INCLUDED 1
#include <EntitiesV/EnvironmentMarker.h>
#include <EntitiesV/WatchPlayers.h>
extern "C" DECL_DLL CDLLEntityClass CEnvironmentBase_DLLClass;
class CEnvironmentBase : public CMovableEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  CTString m_strDescription;
  RANGE m_fDistance;
  FLOAT m_fStretch;
  CEntityPointer m_penTarget;
  CEntityPointer m_penWatcher;
  FLOAT m_fWatcherFrequency;
  FLOAT3D m_vDesiredPosition;
  FLOAT m_fMoveSpeed;
  FLOAT m_fRotateSpeed;
  FLOAT m_fMoveFrequency;
  BOOL m_bUseWatcher;
  BOOL m_bFlying;
  FLOAT m_fWaitTime;
  CTFileName m_fnMdl;
  CTFileName m_fnTex;
  ANIMATION m_iAnim;
  CTFileName m_fnAtt1Mdl;
  CTFileName m_fnAtt1Tex;
  INDEX m_iAtt1Position;
  ANIMATION m_iAtt1Anim;
  CTFileName m_fnAtt2Mdl;
  CTFileName m_fnAtt2Tex;
  INDEX m_iAtt2Position;
  ANIMATION m_iAtt2Anim;
  CTFileName m_fnAtt3Mdl;
  CTFileName m_fnAtt3Tex;
  INDEX m_iAtt3Position;
  ANIMATION m_iAtt3Anim;
   BOOL MovesByTargetedRoute(CTString & strTargetProperty)const;
   BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
   const CTString & GetDescription(void)const;
   CAnimData * GetAnimData(SLONG slPropertyOffset);
   BOOL NextMarker(void);
   void CalcRotation(ANGLE aWantedHeadingRelative,ANGLE3D & aRotation);
   void StopMoving(void);
   void MoveToPosition(void);
   void CalcDestination();
   void MarkerParameters();
   void Initialize(void);
   void InitializeWatcher(FLOAT fWaitTime);
   void PlayDefaultAnim(void);
   void PlayMarkerAnimation(void);
   void ChangeDefaultAnim(void);
   void WaitOnMarker(void);
#define  STATE_CEnvironmentBase_MoveToMarker 0x03840000
  BOOL MoveToMarker(const CEntityEvent &__eeInput);
  BOOL H0x03840001_MoveToMarker_01(const CEntityEvent &__eeInput);
  BOOL H0x03840002_MoveToMarker_02(const CEntityEvent &__eeInput);
  BOOL H0x03840003_MoveToMarker_03(const CEntityEvent &__eeInput);
  BOOL H0x03840004_MoveToMarker_04(const CEntityEvent &__eeInput);
  BOOL H0x03840005_MoveToMarker_05(const CEntityEvent &__eeInput);
#define  STATE_CEnvironmentBase_Activate 0x03840006
  BOOL Activate(const CEntityEvent &__eeInput);
  BOOL H0x03840007_Activate_01(const CEntityEvent &__eeInput);
  BOOL H0x03840008_Activate_02(const CEntityEvent &__eeInput);
#define  STATE_CEnvironmentBase_Stop 0x03840009
  BOOL Stop(const CEntityEvent &__eeInput);
  BOOL H0x0384000a_Stop_01(const CEntityEvent &__eeInput);
  BOOL H0x0384000b_Stop_02(const CEntityEvent &__eeInput);
#define  STATE_CEnvironmentBase_DoAction 0x0384000c
  BOOL DoAction(const CEntityEvent &__eeInput);
  BOOL H0x0384000d_DoAction_01(const CEntityEvent &__eeInput);
  BOOL H0x0384000e_DoAction_02(const CEntityEvent &__eeInput);
  BOOL H0x0384000f_DoAction_03(const CEntityEvent &__eeInput);
  BOOL H0x03840010_DoAction_04(const CEntityEvent &__eeInput);
  BOOL H0x03840011_DoAction_05(const CEntityEvent &__eeInput);
  BOOL H0x03840012_DoAction_06(const CEntityEvent &__eeInput);
  BOOL H0x03840013_DoAction_07(const CEntityEvent &__eeInput);
  BOOL H0x03840014_DoAction_08(const CEntityEvent &__eeInput);
  BOOL H0x03840015_DoAction_09(const CEntityEvent &__eeInput);
  BOOL H0x03840016_DoAction_10(const CEntityEvent &__eeInput);
#define  STATE_CEnvironmentBase_MainLoop 0x03840017
  BOOL MainLoop(const CEntityEvent &__eeInput);
  BOOL H0x03840018_MainLoop_01(const CEntityEvent &__eeInput);
  BOOL H0x03840019_MainLoop_02(const CEntityEvent &__eeInput);
#define  STATE_CEnvironmentBase_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x0384001a_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x0384001b_Main_02(const CEntityEvent &__eeInput);
};

static const char *CEnvironmentBase_propnames[] = {
  "m_strName",
  "m_strDescription",
  "m_fDistance",
  "m_fStretch",
  "m_penTarget",
  "m_penWatcher",
  "m_fWatcherFrequency",
  "m_vDesiredPosition",
  "m_fMoveSpeed",
  "m_fRotateSpeed",
  "m_fMoveFrequency",
  "m_bUseWatcher",
  "m_bFlying",
  "m_fWaitTime",
  "m_fnMdl",
  "m_fnTex",
  "m_iAnim",
  "m_fnAtt1Mdl",
  "m_fnAtt1Tex",
  "m_iAtt1Position",
  "m_iAtt1Anim",
  "m_fnAtt2Mdl",
  "m_fnAtt2Tex",
  "m_iAtt2Position",
  "m_iAtt2Anim",
  "m_fnAtt3Mdl",
  "m_fnAtt3Tex",
  "m_iAtt3Position",
  "m_iAtt3Anim",
};
#define CEnvironmentBase_propnamesct ARRAYCOUNT(CEnvironmentBase_propnames)

#endif // _EntitiesV_EnvironmentBase_INCLUDED
