// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_HazeMarker_INCLUDED
#define _EntitiesV_HazeMarker_INCLUDED 1
#include <EntitiesV/Marker.h>
#include <EntitiesV/FogMarker.h>
extern "C" DECL_DLL CDLLEntityClass CHazeMarker_DLLClass;
class CHazeMarker : public CMarker {
public:
virtual BOOL IsImportant(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  enum FogAttenuationType m_faType;
  FLOAT m_fDensity;
  FLOAT m_fNear;
  FLOAT m_fFar;
  BOOL m_bVisibleFromOutside;
  INDEX m_iSize;
  COLOR m_colBase;
  COLOR m_colUp;
  COLOR m_colDown;
  COLOR m_colNorth;
  COLOR m_colSouth;
  COLOR m_colEast;
  COLOR m_colWest;
   const CTString & GetHazeName(void);
   void GetHaze(class CHazeParameters & hpHaze,FLOAT3D & vViewDir);
#define  STATE_CHazeMarker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};

static const char *CHazeMarker_propnames[] = {
  "m_faType",
  "m_fDensity",
  "m_fNear",
  "m_fFar",
  "m_bVisibleFromOutside",
  "m_iSize",
  "m_colBase",
  "m_colUp",
  "m_colDown",
  "m_colNorth",
  "m_colSouth",
  "m_colEast",
  "m_colWest",
};
#define CHazeMarker_propnamesct ARRAYCOUNT(CHazeMarker_propnames)

#endif // _EntitiesV_HazeMarker_INCLUDED
