// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_KeyItem_INCLUDED
#define _EntitiesV_KeyItem_INCLUDED 1
#include <EntitiesV/Item.h>
extern DECL_DLL CEntityPropertyEnumType KeyItemType_enum;
enum KeyItemType {
  KIT_ANKHWOOD = 0,
  KIT_ANKHROCK = 1,
  KIT_ANKHGOLD = 2,
  KIT_AMONGOLD = 3,
  KIT_ANKHGOLDDUMMY = 4,
  KIT_ELEMENTEARTH = 5,
  KIT_ELEMENTWATER = 6,
  KIT_ELEMENTAIR = 7,
  KIT_ELEMENTFIRE = 8,
  KIT_RAKEY = 9,
  KIT_MOONKEY = 10,
  KIT_EYEOFRA = 12,
  KIT_SCARAB = 13,
  KIT_COBRA = 14,
  KIT_SCARABDUMMY = 15,
  KIT_HEART = 16,
  KIT_FEATHER = 17,
  KIT_SPHINX1 = 18,
  KIT_SPHINX2 = 19,
};
DECL_DLL inline void ClearToDefault(KeyItemType &e) { e = (KeyItemType)0; } ;
#define EVENTCODE_EKey 0x03250000
class DECL_DLL EKey : public CEntityEvent {
public:
EKey();
CEntityEvent *MakeCopy(void);
enum KeyItemType kitType;
};
DECL_DLL inline void ClearToDefault(EKey &e) { e = EKey(); } ;
extern "C" DECL_DLL CDLLEntityClass CKeyItem_DLLClass;
class CKeyItem : public CItem {
public:
virtual BOOL IsImportant(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  enum KeyItemType m_kitType;
  INDEX m_iSoundComponent;
   void Precache(void);
   BOOL FillEntityStatistics(EntityStats * pes);
   void RenderParticles(void);
   void SetProperties(void);
#define  STATE_CKeyItem_ItemCollected 0x03250001
  BOOL ItemCollected(const CEntityEvent &__eeInput);
#define  STATE_CKeyItem_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_KeyItem_INCLUDED
