// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Light_INCLUDED
#define _EntitiesV_Light_INCLUDED 1
#include <EntitiesV/ModelDestruction.h>
#include <EntitiesV/AnimationChanger.h>
extern DECL_DLL CEntityPropertyEnumType LightType_enum;
enum LightType {
  LT_POINT = 0,
  LT_AMBIENT = 1,
  LT_STRONG_AMBIENT = 2,
  LT_DIRECTIONAL = 3,
  LT_STRONG_POINT = 4,
};
DECL_DLL inline void ClearToDefault(LightType &e) { e = (LightType)0; } ;
extern DECL_DLL CEntityPropertyEnumType LensFlareType_enum;
enum LensFlareType {
  LFT_NONE = 0,
  LFT_STANDARD = 1,
  LFT_STANDARD_REFLECTIONS = 2,
  LFT_YELLOW_STAR_RED_RING = 3,
  LFT_WHITE_GLOW_STAR_RED_RING = 4,
  LFT_WHITE_GLOW_STAR = 5,
  LFT_WHITE_STAR_RED_RING_STREAKS = 6,
  LFT_WHITE_STAR_RED_REFLECTIONS = 7,
  LFT_BLUE_STAR_BLUE_REFLECTIONS = 8,
  LFT_PV_SPACE_SHIP_WINDOW_FLARE = 9,
  LFT_WHITE_GLOW_STAR_RED_RING_FAR = 10,
  LFT_WHITE_GLOW_FAR = 11,
  LFT_WHITE_GLOW_STAR_NG = 12,
};
DECL_DLL inline void ClearToDefault(LensFlareType &e) { e = (LensFlareType)0; } ;
extern "C" DECL_DLL CDLLEntityClass CLight_DLLClass;
class CLight : public CEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual const CTString &GetDescription(void) const { return m_strDescription; };
  DECL_DLL virtual void SetDefaultProperties(void);
  COLOR m_colColor;
  COLOR m_colAmbient;
  RANGE m_rFallOffRange;
  RANGE m_rHotSpotRange;
  ILLUMINATIONTYPE m_itIllumination;
  enum LightType m_ltType;
  CTString m_strDescription;
  CTString m_strName;
  BOOL m_bDarkLight;
  FLOAT m_fNearClip;
  FLOAT m_fFarClip;
  BOOL m_bSubstractSectorAmbient;
  BOOL m_bRenderAsSmallLight;
  enum LensFlareType m_lftLensFlare;
  BOOL m_bBackground;
  BOOL m_bLensFlareOnly;
  CTFileName m_fnmLightAnimation;
  ANIMATION m_iLightAnimation;
  FLOAT m_tmOffsetPhase;
  CAnimObject m_aoLightAnimation;
  BOOL m_bTargetable;
  BOOL m_bDynamic;
  BOOL m_bDiffusion;
  CTFileName m_fnmAmbientLightAnimation;
  ANIMATION m_iAmbientLightAnimation;
  CAnimObject m_aoAmbientLightAnimation;
CLightSource m_lsLightSource;
CBoolDefaultFalse m_bdfInitialized;
   CAnimData * GetAnimData(SLONG slPropertyOffset);
   BOOL IsTargetable(void)const;
   BOOL IsImportant(void)const;
   BOOL HandleEvent(const CEntityEvent & ee);
   void MirrorAndStretch(FLOAT fStretch,BOOL bMirrorX);
   CLightSource * GetLightSource(void);
   void SetupLightSource(CLightSource & lsNew);
#define  STATE_CLight_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};

static const char *CLight_propnames[] = {
  "m_colColor",
  "m_colAmbient",
  "m_rFallOffRange",
  "m_rHotSpotRange",
  "m_itIllumination",
  "m_ltType",
  "m_strDescription",
  "m_strName",
  "m_bDarkLight",
  "m_fNearClip",
  "m_fFarClip",
  "m_bSubstractSectorAmbient",
  "m_bRenderAsSmallLight",
  "m_lftLensFlare",
  "m_bBackground",
  "m_bLensFlareOnly",
  "m_fnmLightAnimation",
  "m_iLightAnimation",
  "m_tmOffsetPhase",
  "m_aoLightAnimation",
  "m_bTargetable",
  "m_bDynamic",
  "m_bDiffusion",
  "m_fnmAmbientLightAnimation",
  "m_iAmbientLightAnimation",
  "m_aoAmbientLightAnimation",
};
#define CLight_propnamesct ARRAYCOUNT(CLight_propnames)

#endif // _EntitiesV_Light_INCLUDED
