// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_MovingBrushMarker_INCLUDED
#define _EntitiesV_MovingBrushMarker_INCLUDED 1
#include <EntitiesV/Marker.h>
extern "C" DECL_DLL CDLLEntityClass CMovingBrushMarker_DLLClass;
class CMovingBrushMarker : public CMarker {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  BOOL m_bInverseRotate;
  FLOAT m_fSpeed;
  FLOAT m_fWaitTime;
  BOOL m_bStopMoving;
  enum BoolEType m_betMoveOnTouch;
  FLOAT m_fBlockDamage;
  enum EventEType m_eetMarkerEvent;
  CEntityPointer m_penMarkerEvent;
  enum EventEType m_eetTouchEvent;
  CEntityPointer m_penTouchEvent;
  CEntityPointer m_penSoundStart;
  CEntityPointer m_penSoundStop;
  CEntityPointer m_penSoundFollow;
   BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
#define  STATE_CMovingBrushMarker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_MovingBrushMarker_INCLUDED
