// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Pipebomb_INCLUDED
#define _EntitiesV_Pipebomb_INCLUDED 1
#include <EntitiesV/BasicEffects.h>
#include <EntitiesV/Light.h>
#include <EntitiesV/AmmoItem.h>
#define EVENTCODE_EDropPipebomb 0x01f70000
class DECL_DLL EDropPipebomb : public CEntityEvent {
public:
EDropPipebomb();
CEntityEvent *MakeCopy(void);
CEntityPointer penLauncher;
FLOAT fSpeed;
};
DECL_DLL inline void ClearToDefault(EDropPipebomb &e) { e = EDropPipebomb(); } ;
extern "C" DECL_DLL CDLLEntityClass CPipebomb_DLLClass;
class CPipebomb : public CMovableModelEntity {
public:
virtual CEntity *GetPredictionPair(void) { return m_penPrediction; };
virtual void SetPredictionPair(CEntity *penPair) { m_penPrediction = penPair; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CEntityPointer m_penLauncher;
  FLOAT m_fIgnoreTime;
  FLOAT m_fSpeed;
  BOOL m_bCollected;
  CEntityPointer m_penPrediction;
CLightSource m_lsLightSource;
   void Read_t(CTStream * istr);
   CLightSource * GetLightSource(void);
   void SetupLightSource(void);
   void RenderParticles(void);
   void Pipebomb(void);
   void PipebombExplosion(void);
   void ProjectileHitted(void);
   void SpawnEffect(const CPlacement3D & plEffect,const ESpawnEffect & eSpawnEffect);
#define  STATE_CPipebomb_ProjectileSlide 0x01f70001
  BOOL ProjectileSlide(const CEntityEvent &__eeInput);
  BOOL H0x01f70002_ProjectileSlide_01(const CEntityEvent &__eeInput);
  BOOL H0x01f70003_ProjectileSlide_02(const CEntityEvent &__eeInput);
#define  STATE_CPipebomb_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x01f70004_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01f70005_Main_02(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_Pipebomb_INCLUDED
