// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#define ENTITYCLASS CPlayerMarker

CEntityProperty CPlayerMarker_properties[] = {
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000194<<8)+1, offsetof(CPlayerMarker, m_fHealth), "Health", 'H', "m_fHealth", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000194<<8)+2, offsetof(CPlayerMarker, m_fShield), "Shield", 'S', "m_fShield", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_INDEX, NULL, (0x00000194<<8)+3, offsetof(CPlayerMarker, m_iGiveWeapons), "Give Weapons", 'W', "m_iGiveWeapons", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_INDEX, NULL, (0x00000194<<8)+4, offsetof(CPlayerMarker, m_iTakeWeapons), "Take Weapons", 0, "m_iTakeWeapons", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_STRING, NULL, (0x00000194<<8)+5, offsetof(CPlayerMarker, m_strGroup), "Group", 'G', "m_strGroup", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x00000194<<8)+6, offsetof(CPlayerMarker, m_bQuickStart), "Quick start", 'Q', "m_bQuickStart", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x00000194<<8)+7, offsetof(CPlayerMarker, m_bStartInComputer), "Start in computer", 'C', "m_bStartInComputer", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x00000194<<8)+8, offsetof(CPlayerMarker, m_penMessage), "Message", 'M', "m_penMessage", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000194<<8)+9, offsetof(CPlayerMarker, m_fMaxAmmoRatio), "Max ammo ratio", 'A', "m_fMaxAmmoRatio", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000194<<8)+10, offsetof(CPlayerMarker, m_tmLastSpawned), "", 0, "m_tmLastSpawned", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_INDEX, NULL, (0x00000194<<8)+11, offsetof(CPlayerMarker, m_iTakeAmmo), "Take Ammo", 0, "m_iTakeAmmo", 0x7F0000FFUL, 0),
};
#define CPlayerMarker_propertiesct ARRAYCOUNT(CPlayerMarker_properties)

CEntityComponent CPlayerMarker_components[] = {
#define MODEL_MARKER ((0x00000194<<8)+1)
 CEntityComponent(ECT_MODEL, MODEL_MARKER, "EFNM" "Models\\Editor\\PlayerStart.mdl"),
#define TEXTURE_MARKER ((0x00000194<<8)+2)
 CEntityComponent(ECT_TEXTURE, TEXTURE_MARKER, "EFNM" "Models\\Editor\\PlayerStart.tex"),
};
#define CPlayerMarker_componentsct ARRAYCOUNT(CPlayerMarker_components)

CEventHandlerEntry CPlayerMarker_handlers[] = {
 {1, -1, CEntity::pEventHandler(&CPlayerMarker::Main),DEBUGSTRING("CPlayerMarker::Main")},
};
#define CPlayerMarker_handlersct ARRAYCOUNT(CPlayerMarker_handlers)

CEntity *CPlayerMarker_New(void) { return new CPlayerMarker; };
void CPlayerMarker_OnInitClass(void) {};
void CPlayerMarker_OnEndClass(void) {};
void CPlayerMarker_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CPlayerMarker_OnWorldEnd(CWorld *pwo) {};
void CPlayerMarker_OnWorldInit(CWorld *pwo) {};
void CPlayerMarker_OnWorldTick(CWorld *pwo) {};
void CPlayerMarker_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CPlayerMarker, CMarker, "Player Marker", "Thumbnails\\PlayerMarker.tbn", 0x00000194);
DECLARE_CTFILENAME(_fnmCPlayerMarker_tbn, "Thumbnails\\PlayerMarker.tbn");
