// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Walker_INCLUDED
#define _EntitiesV_Walker_INCLUDED 1
#include <EntitiesV/EnemyBase.h>
#include <EntitiesV/Projectile.h>
extern DECL_DLL CEntityPropertyEnumType WalkerChar_enum;
enum WalkerChar {
  WLC_SOLDIER = 0,
  WLC_SERGEANT = 1,
};
DECL_DLL inline void ClearToDefault(WalkerChar &e) { e = (WalkerChar)0; } ;
extern "C" DECL_DLL CDLLEntityClass CWalker_DLLClass;
class CWalker : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  enum WalkerChar m_EwcChar;
  INDEX m_iLoopCounter;
  FLOAT m_fSize;
  BOOL m_bWalkSoundPlaying;
  FLOAT m_fThreatDistance;
  CSoundObject m_soFeet;
  CSoundObject m_soFire1;
  CSoundObject m_soFire2;
  CSoundObject m_soFire3;
  CSoundObject m_soFire4;
  virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
  virtual const CTFileName & GetComputerMessageName(void)const;
   FLOAT GetThreatDistance(void);
   BOOL ForcesCannonballToExplode(void);
   void Precache(void);
   void * GetEntityInfo(void);
   FLOAT GetCrushHealth(void);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   void StandingAnim(void);
   void StandingAnimFight(void);
   void WalkingAnim(void);
   void RunningAnim(void);
   void RotatingAnim(void);
   void IdleSound(void);
   void SightSound(void);
   void DeathSound(void);
   void ActivateWalkingSound(void);
   void DeactivateWalkingSound(void);
   void FireDeathRocket(FLOAT3D & vPos);
   void FireDeathLaser(FLOAT3D & vPos);
   void EnemyPostInit(void);
#define  STATE_CWalker_Fire 0x01440000
  BOOL Fire(const CEntityEvent &__eeInput);
  BOOL H0x01440001_Fire_01(const CEntityEvent &__eeInput);
  BOOL H0x01440002_Fire_02(const CEntityEvent &__eeInput);
  BOOL H0x01440003_Fire_03(const CEntityEvent &__eeInput);
  BOOL H0x01440004_Fire_04(const CEntityEvent &__eeInput);
  BOOL H0x01440005_Fire_05(const CEntityEvent &__eeInput);
  BOOL H0x01440006_Fire_06(const CEntityEvent &__eeInput);
  BOOL H0x01440007_Fire_07(const CEntityEvent &__eeInput);
  BOOL H0x01440008_Fire_08(const CEntityEvent &__eeInput);
  BOOL H0x01440009_Fire_09(const CEntityEvent &__eeInput);
  BOOL H0x0144000a_Fire_10(const CEntityEvent &__eeInput);
  BOOL H0x0144000b_Fire_11(const CEntityEvent &__eeInput);
  BOOL H0x0144000c_Fire_12(const CEntityEvent &__eeInput);
  BOOL H0x0144000d_Fire_13(const CEntityEvent &__eeInput);
  BOOL H0x0144000e_Fire_14(const CEntityEvent &__eeInput);
  BOOL H0x0144000f_Fire_15(const CEntityEvent &__eeInput);
#define  STATE_CWalker_Death 0x01440010
  BOOL Death(const CEntityEvent &__eeInput);
  BOOL H0x01440011_Death_01(const CEntityEvent &__eeInput);
  BOOL H0x01440012_Death_02(const CEntityEvent &__eeInput);
  BOOL H0x01440013_Death_03(const CEntityEvent &__eeInput);
  BOOL H0x01440014_Death_04(const CEntityEvent &__eeInput);
#define  STATE_CWalker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_Walker_INCLUDED
