// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_ArmorItem_INCLUDED
#define _EntitiesV_ArmorItem_INCLUDED 1
#include <EntitiesV/Item.h>
extern DECL_DLL CEntityPropertyEnumType ArmorItemType_enum;
enum ArmorItemType {
  ARIT_SHARD = 0,
  ARIT_SMALL = 1,
  ARIT_MEDIUM = 2,
  ARIT_STRONG = 3,
  ARIT_SUPER = 4,
  ARIT_HELM = 5,
};
DECL_DLL inline void ClearToDefault(ArmorItemType &e) { e = (ArmorItemType)0; } ;
#define EVENTCODE_EArmor 0x03240000
class DECL_DLL EArmor : public CEntityEvent {
public:
EArmor();
CEntityEvent *MakeCopy(void);
FLOAT fArmor;
BOOL bOverTopArmor;
};
DECL_DLL inline void ClearToDefault(EArmor &e) { e = EArmor(); } ;
extern "C" DECL_DLL CDLLEntityClass CArmorItem_DLLClass;
class CArmorItem : public CItem {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  enum ArmorItemType m_EaitType;
  BOOL m_bOverTopArmor;
  INDEX m_iSoundComponent;
   void Precache(void);
   BOOL FillEntityStatistics(EntityStats * pes);
   void RenderParticles(void);
   void SetProperties(void);
   void AdjustDifficulty(void);
#define  STATE_CArmorItem_ItemCollected 0x03240001
  BOOL ItemCollected(const CEntityEvent &__eeInput);
#define  STATE_CArmorItem_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};

static const char *CArmorItem_propnames[] = {
  "m_EaitType",
  "m_bOverTopArmor",
  "m_iSoundComponent",
};
#define CArmorItem_propnamesct ARRAYCOUNT(CArmorItem_propnames)

#endif // _EntitiesV_ArmorItem_INCLUDED
