// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_BackgroundViewer_INCLUDED
#define _EntitiesV_BackgroundViewer_INCLUDED 1
#include <EntitiesV/Marker.h>
extern "C" DECL_DLL CDLLEntityClass CBackgroundViewer_DLLClass;
class CBackgroundViewer : public CMarker {
public:
virtual BOOL IsImportant(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  BOOL m_bActive;
  CEntityPointer m_penWorldSettingsController;
   BOOL IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget);
   BOOL HandleEvent(const CEntityEvent & ee);
#define  STATE_CBackgroundViewer_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};

static const char *CBackgroundViewer_propnames[] = {
  "m_bActive",
  "m_penWorldSettingsController",
};
#define CBackgroundViewer_propnamesct ARRAYCOUNT(CBackgroundViewer_propnames)

#endif // _EntitiesV_BackgroundViewer_INCLUDED
