// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_ChainsawFreak_INCLUDED
#define _EntitiesV_ChainsawFreak_INCLUDED 1
#include <EntitiesV/EnemyBase.h>
#include <EntitiesV/EnemyRunInto.h>
extern "C" DECL_DLL CDLLEntityClass CChainsawFreak_DLLClass;
class CChainsawFreak : public CEnemyRunInto {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  BOOL m_bRunAttack;
  BOOL m_bSawHit;
  CEntityPointer m_penLastTouched;
  CSoundObject m_soFeet;
  BOOL m_bRunSoundPlaying;
  INDEX m_iRunType;
  BOOL m_bAttacking;
  FLOAT m_fSightSoundBegin;
  virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
   void Precache(void);
   void * GetEntityInfo(void);
   FLOAT GetCrushHealth(void);
  virtual const CTFileName & GetComputerMessageName(void)const;
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   void AdjustDifficulty(void);
   INDEX AnimForDeath(void);
   FLOAT WaitForDust(FLOAT3D & vStretch);
   void DeathNotify();
   void StandingAnim(void);
   void WalkingAnim(void);
   void RunningAnim(void);
   void ChargeAnim(void);
   void RotatingAnim(void);
   void IdleSound(void);
   void WoundSound(void);
   void DeathSound(void);
   void ActivateRunningSound(void);
   void DeactivateRunningSound(void);
   void LiveEntityTouched(ETouch etouch);
   BOOL HigherMass(void);
   void EnemyPostInit(void);
   void PreMoving();
#define  STATE_CChainsawFreak_Hit 0x01560000
  BOOL Hit(const CEntityEvent &__eeInput);
  BOOL H0x01560001_Hit_01(const CEntityEvent &__eeInput);
  BOOL H0x01560002_Hit_02(const CEntityEvent &__eeInput);
  BOOL H0x01560003_Hit_03(const CEntityEvent &__eeInput);
  BOOL H0x01560004_Hit_04(const CEntityEvent &__eeInput);
  BOOL H0x01560005_Hit_05(const CEntityEvent &__eeInput);
  BOOL H0x01560006_Hit_06(const CEntityEvent &__eeInput);
  BOOL H0x01560007_Hit_07(const CEntityEvent &__eeInput);
  BOOL H0x01560008_Hit_08(const CEntityEvent &__eeInput);
  BOOL H0x01560009_Hit_09(const CEntityEvent &__eeInput);
#define  STATE_CChainsawFreak_AttackEnemy 0x0156000a
  BOOL AttackEnemy(const CEntityEvent &__eeInput);
#define  STATE_CChainsawFreak_BeIdle 0x0156000b
  BOOL BeIdle(const CEntityEvent &__eeInput);
#define  STATE_CChainsawFreak_PostRunAwayFromEnemy 0x0156000c
  BOOL PostRunAwayFromEnemy(const CEntityEvent &__eeInput);
  BOOL H0x0156000d_PostRunAwayFromEnemy_01(const CEntityEvent &__eeInput);
  BOOL H0x0156000e_PostRunAwayFromEnemy_02(const CEntityEvent &__eeInput);
  BOOL H0x0156000f_PostRunAwayFromEnemy_03(const CEntityEvent &__eeInput);
  BOOL H0x01560010_PostRunAwayFromEnemy_04(const CEntityEvent &__eeInput);
#define  STATE_CChainsawFreak_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_ChainsawFreak_INCLUDED
