// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_DevilMarker_INCLUDED
#define _EntitiesV_DevilMarker_INCLUDED 1
#include <EntitiesV/Marker.h>
#include <EntitiesV/Devil.h>
extern DECL_DLL CEntityPropertyEnumType DevilActionType_enum;
enum DevilActionType {
  DAT_NONE = 0,
  DAT_WALK = 1,
  DAT_RISE = 2,
  DAT_ROAR = 3,
  DAT_PUNCH_LEFT = 4,
  DAT_PUNCH_RIGHT = 5,
  DAT_HIT_GROUND = 6,
  DAT_JUMP = 7,
  DAT_WAIT = 8,
  DAT_STOP_DESTROYING = 9,
  DAT_NEXT_ACTION = 10,
  DAT_GRAB_LOWER_WEAPONS = 11,
  DAT_STOP_MOVING = 12,
  DAT_JUMP_INTO_PYRAMID = 13,
  DAT_SMASH_LEFT = 14,
  DAT_SMASH_RIGHT = 15,
  DAT_PUNCH = 16,
  DAT_SMASH = 17,
  DAT_FORCE_ATTACK_RADIUS = 18,
  DAT_TELEPORT_INTO_PYRAMID = 19,
  DAT_DECREASE_ATTACK_RADIUS = 20,
};
DECL_DLL inline void ClearToDefault(DevilActionType &e) { e = (DevilActionType)0; } ;
extern "C" DECL_DLL CDLLEntityClass CDevilMarker_DLLClass;
class CDevilMarker : public CMarker {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  enum DevilActionType m_datType;
  INDEX m_iWaitIdles;
  CEntityPointer m_penDevil;
  CEntityPointer m_penTrigger;
  CEntityPointer m_penToDestroy1;
  CEntityPointer m_penToDestroy2;
  RANGE m_fAttackRadius;
   void SetDefaultName(void);
   const CTString & GetDescription(void)const;
   BOOL MovesByTargetedRoute(CTString & strTargetProperty)const;
   BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
   BOOL HandleEvent(const CEntityEvent & ee);
#define  STATE_CDevilMarker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_DevilMarker_INCLUDED
