// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_EnemyCounter_INCLUDED
#define _EntitiesV_EnemyCounter_INCLUDED 1
#define CEnemyCounter_ClassID 339
extern "C" DECL_DLL CDLLEntityClass CEnemyCounter_DLLClass;
class CEnemyCounter : public CRationalEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CEntityPointer m_penMainMusicHolder;
  CTString m_strName;
  INDEX m_iCountFrom;
  INDEX m_iCount;
   class CMusicHolder * GetMusicHolder();
   void StartCounting(void);
   void CountOne(void);
   void StopCounting(void);
#define  STATE_CEnemyCounter_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x01530000_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01530001_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x01530002_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x01530003_Main_04(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_EnemyCounter_INCLUDED
