// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#define ENTITYCLASS CExotechLarvaAnimator

CEntityProperty CExotechLarvaAnimator_properties[] = {
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x00000196<<8)+1, offsetof(CExotechLarvaAnimator, m_penLarva), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x00000196<<8)+255, offsetof(CExotechLarvaAnimator, m_penPrediction), "", 0, 0, 0),
};
#define CExotechLarvaAnimator_propertiesct ARRAYCOUNT(CExotechLarvaAnimator_properties)

CEntityComponent CExotechLarvaAnimator_components[] = {
  CEntityComponent()
};
#define CExotechLarvaAnimator_componentsct 0


CEventHandlerEntry CExotechLarvaAnimator_handlers[] = {
 {1, -1, CEntity::pEventHandler(&CExotechLarvaAnimator::Main),DEBUGSTRING("CExotechLarvaAnimator::Main")},
 {0x01960001, -1, CEntity::pEventHandler(&CExotechLarvaAnimator::H0x01960001_Main_01), DEBUGSTRING("CExotechLarvaAnimator::H0x01960001_Main_01")},
 {0x01960002, -1, CEntity::pEventHandler(&CExotechLarvaAnimator::H0x01960002_Main_02), DEBUGSTRING("CExotechLarvaAnimator::H0x01960002_Main_02")},
};
#define CExotechLarvaAnimator_handlersct ARRAYCOUNT(CExotechLarvaAnimator_handlers)

CEntity *CExotechLarvaAnimator_New(void) { return new CExotechLarvaAnimator; };
void CExotechLarvaAnimator_OnInitClass(void) {};
void CExotechLarvaAnimator_OnEndClass(void) {};
void CExotechLarvaAnimator_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CExotechLarvaAnimator_OnWorldEnd(CWorld *pwo) {};
void CExotechLarvaAnimator_OnWorldInit(CWorld *pwo) {};
void CExotechLarvaAnimator_OnWorldTick(CWorld *pwo) {};
void CExotechLarvaAnimator_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CExotechLarvaAnimator, CRationalEntity, "ExotechLarvaAnimator", "", 0x00000196);
DECLARE_CTFILENAME(_fnmCExotechLarvaAnimator_tbn, "");
