// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_ExotechLarvaAnimator_INCLUDED
#define _EntitiesV_ExotechLarvaAnimator_INCLUDED 1
#include <EntitiesV/ExotechLarva.h>
#define EVENTCODE_ELarvaAnimatorInit 0x01960000
class DECL_DLL ELarvaAnimatorInit : public CEntityEvent {
public:
ELarvaAnimatorInit();
CEntityEvent *MakeCopy(void);
CEntityPointer penLarva;
};
DECL_DLL inline void ClearToDefault(ELarvaAnimatorInit &e) { e = ELarvaAnimatorInit(); } ;
extern "C" DECL_DLL CDLLEntityClass CExotechLarvaAnimator_DLLClass;
class DECL_DLL  CExotechLarvaAnimator : public CRationalEntity {
public:
virtual CEntity *GetPredictionPair(void) { return m_penPrediction; };
virtual void SetPredictionPair(CEntity *penPair) { m_penPrediction = penPair; };
   virtual void SetDefaultProperties(void);
  CEntityPointer m_penLarva;
  CEntityPointer m_penPrediction;
   CExotechLarva * GetLarva(void);
#define  STATE_CExotechLarvaAnimator_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x01960001_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01960002_Main_02(const CEntityEvent &__eeInput);
};

static const char *CExotechLarvaAnimator_propnames[] = {
  "m_penLarva",
  "m_penPrediction",
};
#define CExotechLarvaAnimator_propnamesct ARRAYCOUNT(CExotechLarvaAnimator_propnames)

#endif // _EntitiesV_ExotechLarvaAnimator_INCLUDED
