// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Fishman_INCLUDED
#define _EntitiesV_Fishman_INCLUDED 1
#include <EntitiesV/EnemyDive.h>
extern "C" DECL_DLL CDLLEntityClass CFishman_DLLClass;
class CFishman : public CEnemyDive {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
   void * GetEntityInfo(void);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   INDEX AnimForDamage(FLOAT fDamage);
   INDEX AnimForDeath(void);
   void DeathNotify(void);
   void StandingAnim(void);
   void WalkingAnim(void);
   void RunningAnim(void);
   void RotatingAnim(void);
   void ChangeCollisionToLiquid();
   void ChangeCollisionToGround();
   void IdleSound(void);
   void SightSound(void);
   void WoundSound(void);
   void DeathSound(void);
#define  STATE_CFishman_DiveFire 0x01480000
  BOOL DiveFire(const CEntityEvent &__eeInput);
  BOOL H0x01480001_DiveFire_01(const CEntityEvent &__eeInput);
  BOOL H0x01480002_DiveFire_02(const CEntityEvent &__eeInput);
  BOOL H0x01480003_DiveFire_03(const CEntityEvent &__eeInput);
  BOOL H0x01480004_DiveFire_04(const CEntityEvent &__eeInput);
  BOOL H0x01480005_DiveFire_05(const CEntityEvent &__eeInput);
  BOOL H0x01480006_DiveFire_06(const CEntityEvent &__eeInput);
#define  STATE_CFishman_DiveHit 0x01480007
  BOOL DiveHit(const CEntityEvent &__eeInput);
  BOOL H0x01480008_DiveHit_01(const CEntityEvent &__eeInput);
  BOOL H0x01480009_DiveHit_02(const CEntityEvent &__eeInput);
  BOOL H0x0148000a_DiveHit_03(const CEntityEvent &__eeInput);
  BOOL H0x0148000b_DiveHit_04(const CEntityEvent &__eeInput);
  BOOL H0x0148000c_DiveHit_05(const CEntityEvent &__eeInput);
  BOOL H0x0148000d_DiveHit_06(const CEntityEvent &__eeInput);
#define  STATE_CFishman_Fire 0x0148000e
  BOOL Fire(const CEntityEvent &__eeInput);
  BOOL H0x0148000f_Fire_01(const CEntityEvent &__eeInput);
  BOOL H0x01480010_Fire_02(const CEntityEvent &__eeInput);
  BOOL H0x01480011_Fire_03(const CEntityEvent &__eeInput);
  BOOL H0x01480012_Fire_04(const CEntityEvent &__eeInput);
  BOOL H0x01480013_Fire_05(const CEntityEvent &__eeInput);
  BOOL H0x01480014_Fire_06(const CEntityEvent &__eeInput);
  BOOL H0x01480015_Fire_07(const CEntityEvent &__eeInput);
  BOOL H0x01480016_Fire_08(const CEntityEvent &__eeInput);
  BOOL H0x01480017_Fire_09(const CEntityEvent &__eeInput);
#define  STATE_CFishman_Hit 0x01480018
  BOOL Hit(const CEntityEvent &__eeInput);
  BOOL H0x01480019_Hit_01(const CEntityEvent &__eeInput);
  BOOL H0x0148001a_Hit_02(const CEntityEvent &__eeInput);
  BOOL H0x0148001b_Hit_03(const CEntityEvent &__eeInput);
  BOOL H0x0148001c_Hit_04(const CEntityEvent &__eeInput);
  BOOL H0x0148001d_Hit_05(const CEntityEvent &__eeInput);
  BOOL H0x0148001e_Hit_06(const CEntityEvent &__eeInput);
  BOOL H0x0148001f_Hit_07(const CEntityEvent &__eeInput);
  BOOL H0x01480020_Hit_08(const CEntityEvent &__eeInput);
  BOOL H0x01480021_Hit_09(const CEntityEvent &__eeInput);
  BOOL H0x01480022_Hit_10(const CEntityEvent &__eeInput);
  BOOL H0x01480023_Hit_11(const CEntityEvent &__eeInput);
#define  STATE_CFishman_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_Fishman_INCLUDED
