// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_GradientMarker_INCLUDED
#define _EntitiesV_GradientMarker_INCLUDED 1
#include <EntitiesV/Marker.h>
#include <EntitiesV/WorldBase.h>
extern "C" DECL_DLL CDLLEntityClass CGradientMarker_DLLClass;
class CGradientMarker : public CMarker {
public:
virtual BOOL IsImportant(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  FLOAT m_fHeight;
  BOOL m_bDarkLight;
  COLOR m_colColor0;
  COLOR m_colColor1;
   const CTString & GetGradientName(void);
   BOOL GetGradient(INDEX iGradient,class CGradientParameters & gpGradient);
   void UncacheShadowsForGradient(void);
   void SetPlacement_internal(const CPlacement3D & plNew,const FLOATmatrix3D & mRotation,BOOL bNear);
   void OnEnd(void);
#define  STATE_CGradientMarker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};

static const char *CGradientMarker_propnames[] = {
  "m_fHeight",
  "m_bDarkLight",
  "m_colColor0",
  "m_colColor1",
};
#define CGradientMarker_propnamesct ARRAYCOUNT(CGradientMarker_propnames)

#endif // _EntitiesV_GradientMarker_INCLUDED
