// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Guffy_INCLUDED
#define _EntitiesV_Guffy_INCLUDED 1
#include <EntitiesV/EnemyBase.h>
#include <EntitiesV/Projectile.h>
extern "C" DECL_DLL CDLLEntityClass CGuffy_DLLClass;
class CGuffy : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  INDEX m_iLoopCounter;
  FLOAT m_fSize;
  BOOL m_bWalkSoundPlaying;
  FLOAT m_fThreatDistance;
  BOOL m_bEnemyToTheLeft;
  CSoundObject m_soFire1;
  CSoundObject m_soFire2;
  virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
  virtual const CTFileName & GetComputerMessageName(void)const;
   void Precache(void);
   void * GetEntityInfo(void);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   void StandingAnim(void);
   void RunningAnim(void);
   void WalkingAnim(void);
   void RotatingAnim(void);
   void IdleSound(void);
   void SightSound(void);
   void WoundSound(void);
   void DeathSound(void);
   void FireRocket(FLOAT3D & vPos);
   void EnemyPostInit(void);
   INDEX AnimForDamage(FLOAT fDamage);
   INDEX AnimForDeath(void);
   FLOAT WaitForDust(FLOAT3D & vStretch);
#define  STATE_CGuffy_Fire 0x01580000
  BOOL Fire(const CEntityEvent &__eeInput);
  BOOL H0x01580001_Fire_01(const CEntityEvent &__eeInput);
  BOOL H0x01580002_Fire_02(const CEntityEvent &__eeInput);
  BOOL H0x01580003_Fire_03(const CEntityEvent &__eeInput);
  BOOL H0x01580004_Fire_04(const CEntityEvent &__eeInput);
  BOOL H0x01580005_Fire_05(const CEntityEvent &__eeInput);
  BOOL H0x01580006_Fire_06(const CEntityEvent &__eeInput);
#define  STATE_CGuffy_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_Guffy_INCLUDED
