// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_HudPicHolder_INCLUDED
#define _EntitiesV_HudPicHolder_INCLUDED 1
extern "C" DECL_DLL CDLLEntityClass CHudPicHolder_DLLClass;
class CHudPicHolder : public CRationalEntity {
public:
virtual BOOL IsTargetable(void) const { return TRUE; };
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsImportant(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  CTString m_strDescription;
  CTFileName m_fnmPicture;
  FLOAT m_tmFadeInStart;
  FLOAT m_tmFadeOutStart;
  FLOAT m_tmFadeInLen;
  FLOAT m_tmFadeOutLen;
  FLOAT m_tmAutoFadeOut;
  FLOAT m_fYRatio;
  FLOAT m_fXRatio;
  FLOAT m_fPictureStretch;
   const CTString & GetDescription(void)const;
   BOOL ReloadData(void);
   BOOL LoadOneFile(const CTFileName & fnm);
   BOOL Picture_On(CTFileName fnPic);
   void Picture_Off(void);
   FLOAT HudPic_Render(CHudPicHolder * penThis,CDrawPort * pdp);
#define  STATE_CHudPicHolder_WaitAndFadeOut 0x00f10000
  BOOL WaitAndFadeOut(const CEntityEvent &__eeInput);
  BOOL H0x00f10001_WaitAndFadeOut_01(const CEntityEvent &__eeInput);
  BOOL H0x00f10002_WaitAndFadeOut_02(const CEntityEvent &__eeInput);
#define  STATE_CHudPicHolder_ApplyFadeOut 0x00f10003
  BOOL ApplyFadeOut(const CEntityEvent &__eeInput);
  BOOL H0x00f10004_ApplyFadeOut_01(const CEntityEvent &__eeInput);
  BOOL H0x00f10005_ApplyFadeOut_02(const CEntityEvent &__eeInput);
  BOOL H0x00f10006_ApplyFadeOut_03(const CEntityEvent &__eeInput);
#define  STATE_CHudPicHolder_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x00f10007_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x00f10008_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x00f10009_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x00f1000a_Main_04(const CEntityEvent &__eeInput);
};

static const char *CHudPicHolder_propnames[] = {
  "m_strName",
  "m_strDescription",
  "m_fnmPicture",
  "m_tmFadeInStart",
  "m_tmFadeOutStart",
  "m_tmFadeInLen",
  "m_tmFadeOutLen",
  "m_tmAutoFadeOut",
  "m_fYRatio",
  "m_fXRatio",
  "m_fPictureStretch",
};
#define CHudPicHolder_propnamesct ARRAYCOUNT(CHudPicHolder_propnames)

#endif // _EntitiesV_HudPicHolder_INCLUDED
