// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_KeyItem_INCLUDED
#define _EntitiesV_KeyItem_INCLUDED 1
#include <EntitiesV/Item.h>
extern DECL_DLL CEntityPropertyEnumType KeyItemType_enum;
enum KeyItemType {
  KIT_BOOKOFWISDOM = 0,
  KIT_CROSSWOODEN = 1,
  KIT_CROSSMETAL = 2,
  KIT_CROSSGOLD = 3,
  KIT_JAGUARGOLDDUMMY = 4,
  KIT_HAWKWINGS01DUMMY = 5,
  KIT_HAWKWINGS02DUMMY = 6,
  KIT_HOLYGRAIL = 7,
  KIT_TABLESDUMMY = 8,
  KIT_WINGEDLION = 9,
  KIT_ELEPHANTGOLD = 10,
  KIT_STATUEHEAD01 = 11,
  KIT_STATUEHEAD02 = 12,
  KIT_STATUEHEAD03 = 13,
  KIT_KINGSTATUE = 14,
  KIT_CRYSTALSKULL = 15,
};
DECL_DLL inline void ClearToDefault(KeyItemType &e) { e = (KeyItemType)0; } ;
#define EVENTCODE_EKey 0x03250000
class DECL_DLL EKey : public CEntityEvent {
public:
EKey();
CEntityEvent *MakeCopy(void);
enum KeyItemType kitType;
};
DECL_DLL inline void ClearToDefault(EKey &e) { e = EKey(); } ;
extern "C" DECL_DLL CDLLEntityClass CKeyItem_DLLClass;
class CKeyItem : public CItem {
public:
virtual BOOL IsImportant(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  enum KeyItemType m_kitType;
  INDEX m_iSoundComponent;
  FLOAT m_fSize;
   void Precache(void);
   BOOL FillEntityStatistics(EntityStats * pes);
   void RenderParticles(void);
   void SetProperties(void);
#define  STATE_CKeyItem_ItemCollected 0x03250001
  BOOL ItemCollected(const CEntityEvent &__eeInput);
#define  STATE_CKeyItem_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_KeyItem_INCLUDED
