// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_LarvaOffspring_INCLUDED
#define _EntitiesV_LarvaOffspring_INCLUDED 1
#include <EntitiesV/BasicEffects.h>
#include <EntitiesV/Light.h>
#include <EntitiesV/Flame.h>
#define EVENTCODE_ELaunchLarvaOffspring 0x01610000
class DECL_DLL ELaunchLarvaOffspring : public CEntityEvent {
public:
ELaunchLarvaOffspring();
CEntityEvent *MakeCopy(void);
CEntityPointer penLauncher;
};
DECL_DLL inline void ClearToDefault(ELaunchLarvaOffspring &e) { e = ELaunchLarvaOffspring(); } ;
extern "C" DECL_DLL CDLLEntityClass CLarvaOffspring_DLLClass;
class DECL_DLL  CLarvaOffspring : public CMovableModelEntity {
public:
virtual CEntity *GetPredictionPair(void) { return m_penPrediction; };
virtual void SetPredictionPair(CEntity *penPair) { m_penPrediction = penPair; };
   virtual void SetDefaultProperties(void);
  CEntityPointer m_penLauncher;
  CEntityPointer m_penTarget;
  FLOAT m_fIgnoreTime;
  FLOAT m_fFlyTime;
  FLOAT m_fStartTime;
  FLOAT m_fDamageAmount;
  FLOAT m_fRangeDamageAmount;
  FLOAT m_fDamageHotSpotRange;
  FLOAT m_fDamageFallOffRange;
  FLOAT m_fSoundRange;
  BOOL m_bExplode;
  FLOAT m_aRotateSpeed;
  FLOAT m_tmExpandBox;
  CSoundObject m_soEffect;
  BOOL bLockedOn;
  CEntityPointer m_penPrediction;
   void PreMoving(void);
   void Precache();
   void InitializeProjectile(void);
   void LarvaTailExplosion(void);
   void ProjectileTouch(CEntityPointer penHit);
   void ProjectileHit(void);
   void SpawnEffect(const CPlacement3D & plEffect,const ESpawnEffect & eSpawnEffect);
   ANGLE GetRotationSpeed(ANGLE aWantedAngle,ANGLE aRotateSpeed,FLOAT fWaitFrequency);
#define  STATE_CLarvaOffspring_LarvaOffspringGuidedSlide 0x01610001
  BOOL LarvaOffspringGuidedSlide(const CEntityEvent &__eeInput);
  BOOL H0x01610002_LarvaOffspringGuidedSlide_01(const CEntityEvent &__eeInput);
  BOOL H0x01610003_LarvaOffspringGuidedSlide_02(const CEntityEvent &__eeInput);
  BOOL H0x01610004_LarvaOffspringGuidedSlide_03(const CEntityEvent &__eeInput);
  BOOL H0x01610005_LarvaOffspringGuidedSlide_04(const CEntityEvent &__eeInput);
#define  STATE_CLarvaOffspring_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x01610006_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01610007_Main_02(const CEntityEvent &__eeInput);
};

static const char *CLarvaOffspring_propnames[] = {
  "m_penLauncher",
  "m_penTarget",
  "m_fIgnoreTime",
  "m_fFlyTime",
  "m_fStartTime",
  "m_fDamageAmount",
  "m_fRangeDamageAmount",
  "m_fDamageHotSpotRange",
  "m_fDamageFallOffRange",
  "m_fSoundRange",
  "m_bExplode",
  "m_aRotateSpeed",
  "m_tmExpandBox",
  "m_soEffect",
  "bLockedOn",
  "m_penPrediction",
};
#define CLarvaOffspring_propnamesct ARRAYCOUNT(CLarvaOffspring_propnames)

#endif // _EntitiesV_LarvaOffspring_INCLUDED
