// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_MeteorShower_INCLUDED
#define _EntitiesV_MeteorShower_INCLUDED 1
#include <EntitiesV/Projectile.h>
#include <EntitiesV/EnemyMarker.h>
#define CMeteorShower_ClassID 615
extern "C" DECL_DLL CDLLEntityClass CMeteorShower_DLLClass;
class CMeteorShower : public CRationalEntity {
public:
virtual BOOL IsTargetable(void) const { return TRUE; };
virtual const CTString &GetName(void) const { return m_strName; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  ANGLE3D m_aAngle;
  INDEX m_iPerTickLaunchChance;
  FLOAT m_fMinStretch;
  FLOAT m_fMaxStretch;
  RANGE m_rSafeArea;
  RANGE m_rArea;
  FLOAT m_fSpeed;
  FLOAT m_fLaunchDistance;
   void Precache(void);
   void SpawnProjectile(const CPlacement3D & pl);
   void MaybeShootMeteor(void);
#define  STATE_CMeteorShower_Active 0x02670000
  BOOL Active(const CEntityEvent &__eeInput);
  BOOL H0x02670001_Active_01(const CEntityEvent &__eeInput);
  BOOL H0x02670002_Active_02(const CEntityEvent &__eeInput);
  BOOL H0x02670003_Active_03(const CEntityEvent &__eeInput);
  BOOL H0x02670004_Active_04(const CEntityEvent &__eeInput);
#define  STATE_CMeteorShower_Inactive 0x02670005
  BOOL Inactive(const CEntityEvent &__eeInput);
  BOOL H0x02670006_Inactive_01(const CEntityEvent &__eeInput);
  BOOL H0x02670007_Inactive_02(const CEntityEvent &__eeInput);
#define  STATE_CMeteorShower_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x02670008_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x02670009_Main_02(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_MeteorShower_INCLUDED
