// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_PyramidSpaceShipMarker_INCLUDED
#define _EntitiesV_PyramidSpaceShipMarker_INCLUDED 1
#include <EntitiesV/Marker.h>
extern "C" DECL_DLL CDLLEntityClass CPyramidSpaceShipMarker_DLLClass;
class CPyramidSpaceShipMarker : public CMarker {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  FLOAT m_fDeltaTime;
  FLOAT m_fBias;
  FLOAT m_fTension;
  FLOAT m_fContinuity;
  BOOL m_bStopMoving;
  CEntityPointer m_penTrigger;
  FLOAT m_fRotSpeed;
  CEntityPointer m_penSpaceShip;
   BOOL IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget);
   BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
   BOOL HandleEvent(const CEntityEvent & ee);
#define  STATE_CPyramidSpaceShipMarker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_PyramidSpaceShipMarker_INCLUDED
