// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_SeriousBomb_INCLUDED
#define _EntitiesV_SeriousBomb_INCLUDED 1
#define EVENTCODE_ESeriousBomb 0x01620000
class DECL_DLL ESeriousBomb : public CEntityEvent {
public:
ESeriousBomb();
CEntityEvent *MakeCopy(void);
CEntityPointer penOwner;
};
DECL_DLL inline void ClearToDefault(ESeriousBomb &e) { e = ESeriousBomb(); } ;
extern "C" DECL_DLL CDLLEntityClass CSeriousBomb_DLLClass;
class CSeriousBomb : public CRationalEntity {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  CEntityPointer m_penOwner;
  CSoundObject m_soBlow;
   void ShakeItBaby(FLOAT tmShaketime,FLOAT fPower,FLOAT fFade,BOOL bFadeIn);
   void Glare(FLOAT fStart,FLOAT fEnd,FLOAT fFinR,FLOAT fFoutR);
   void ExplodeBomb(void);
#define  STATE_CSeriousBomb_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x01620001_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01620002_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x01620003_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x01620004_Main_04(const CEntityEvent &__eeInput);
  BOOL H0x01620005_Main_05(const CEntityEvent &__eeInput);
  BOOL H0x01620006_Main_06(const CEntityEvent &__eeInput);
  BOOL H0x01620007_Main_07(const CEntityEvent &__eeInput);
};

static const char *CSeriousBomb_propnames[] = {
  "m_penOwner",
  "m_soBlow",
};
#define CSeriousBomb_propnamesct ARRAYCOUNT(CSeriousBomb_propnames)

#endif // _EntitiesV_SeriousBomb_INCLUDED
