// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Trigger_INCLUDED
#define _EntitiesV_Trigger_INCLUDED 1
extern "C" DECL_DLL CDLLEntityClass CTrigger_DLLClass;
class CTrigger : public CRationalEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  CEntityPointer m_penTarget1;
  CEntityPointer m_penTarget2;
  CEntityPointer m_penTarget3;
  CEntityPointer m_penTarget4;
  CEntityPointer m_penTarget5;
  CEntityPointer m_penTarget6;
  CEntityPointer m_penTarget7;
  CEntityPointer m_penTarget8;
  CEntityPointer m_penTarget9;
  CEntityPointer m_penTarget10;
  enum EventEType m_eetEvent1;
  enum EventEType m_eetEvent2;
  enum EventEType m_eetEvent3;
  enum EventEType m_eetEvent4;
  enum EventEType m_eetEvent5;
  enum EventEType m_eetEvent6;
  enum EventEType m_eetEvent7;
  enum EventEType m_eetEvent8;
  enum EventEType m_eetEvent9;
  enum EventEType m_eetEvent10;
  CTStringTrans m_strMessage;
  FLOAT m_fMessageTime;
  enum MessageSound m_mssMessageSound;
  FLOAT m_fScore;
  FLOAT m_fWaitTime;
  BOOL m_bAutoStart;
  INDEX m_iCount;
  BOOL m_bUseCount;
  BOOL m_bReuseCount;
  BOOL m_bTellCount;
  BOOL m_bActive;
  RANGE m_fSendRange;
  enum EventEType m_eetRange;
  INDEX m_iCountTmp;
  CEntityPointer m_penCaused;
  INDEX m_ctMaxTrigs;
   CEntity * GetTarget(void)const;
#define  STATE_CTrigger_SendEventToTargets 0x00cd0000
  BOOL SendEventToTargets(const CEntityEvent &__eeInput);
  BOOL H0x00cd0001_SendEventToTargets_01(const CEntityEvent &__eeInput);
  BOOL H0x00cd0002_SendEventToTargets_02(const CEntityEvent &__eeInput);
  BOOL H0x00cd0003_SendEventToTargets_03(const CEntityEvent &__eeInput);
#define  STATE_CTrigger_Active 0x00cd0004
  BOOL Active(const CEntityEvent &__eeInput);
  BOOL H0x00cd0005_Active_01(const CEntityEvent &__eeInput);
  BOOL H0x00cd0006_Active_02(const CEntityEvent &__eeInput);
#define  STATE_CTrigger_Inactive 0x00cd0007
  BOOL Inactive(const CEntityEvent &__eeInput);
  BOOL H0x00cd0008_Inactive_01(const CEntityEvent &__eeInput);
  BOOL H0x00cd0009_Inactive_02(const CEntityEvent &__eeInput);
  BOOL H0x00cd000a_Inactive_03(const CEntityEvent &__eeInput);
  BOOL H0x00cd000b_Inactive_04(const CEntityEvent &__eeInput);
  BOOL H0x00cd000c_Inactive_05(const CEntityEvent &__eeInput);
  BOOL H0x00cd000d_Inactive_06(const CEntityEvent &__eeInput);
#define  STATE_CTrigger_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x00cd000e_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x00cd000f_Main_02(const CEntityEvent &__eeInput);
};

static const char *CTrigger_propnames[] = {
  "m_strName",
  "m_penTarget1",
  "m_penTarget2",
  "m_penTarget3",
  "m_penTarget4",
  "m_penTarget5",
  "m_penTarget6",
  "m_penTarget7",
  "m_penTarget8",
  "m_penTarget9",
  "m_penTarget10",
  "m_eetEvent1",
  "m_eetEvent2",
  "m_eetEvent3",
  "m_eetEvent4",
  "m_eetEvent5",
  "m_eetEvent6",
  "m_eetEvent7",
  "m_eetEvent8",
  "m_eetEvent9",
  "m_eetEvent10",
  "m_strMessage",
  "m_fMessageTime",
  "m_mssMessageSound",
  "m_fScore",
  "m_fWaitTime",
  "m_bAutoStart",
  "m_iCount",
  "m_bUseCount",
  "m_bReuseCount",
  "m_bTellCount",
  "m_bActive",
  "m_fSendRange",
  "m_eetRange",
  "m_iCountTmp",
  "m_penCaused",
  "m_ctMaxTrigs",
};
#define CTrigger_propnamesct ARRAYCOUNT(CTrigger_propnames)

#endif // _EntitiesV_Trigger_INCLUDED
