// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Woman_INCLUDED
#define _EntitiesV_Woman_INCLUDED 1
#include <EntitiesV/EnemyFly.h>
extern "C" DECL_DLL CDLLEntityClass CWoman_DLLClass;
class CWoman : public CEnemyFly {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  BOOL m_bKamikazeCarrier;
  RANGE m_rKamikazeDropDistance;
  BOOL m_bKamikazeAttached;
  virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
  virtual const CTFileName & GetComputerMessageName(void)const;
   void Precache(void);
   void * GetEntityInfo(void);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   INDEX AnimForDamage(FLOAT fDamage);
   INDEX AnimForDeath(void);
   FLOAT WaitForDust(FLOAT3D & vStretch);
   void DeathNotify(void);
   void StandingAnim(void);
   void WalkingAnim(void);
   void RunningAnim(void);
   void RotatingAnim(void);
   FLOAT AirToGroundAnim(void);
   FLOAT GroundToAirAnim(void);
   void ChangeCollisionToAir();
   void ChangeCollisionToGround();
   void IdleSound(void);
   void SightSound(void);
   void WoundSound(void);
   void DeathSound(void);
   void AttachKamikaze();
   void RemoveKamikaze();
   void DropKamikaze();
   void PreMoving();
   void BlowUp(void);
#define  STATE_CWoman_FlyFire 0x01400000
  BOOL FlyFire(const CEntityEvent &__eeInput);
  BOOL H0x01400001_FlyFire_01(const CEntityEvent &__eeInput);
  BOOL H0x01400002_FlyFire_02(const CEntityEvent &__eeInput);
  BOOL H0x01400003_FlyFire_03(const CEntityEvent &__eeInput);
  BOOL H0x01400004_FlyFire_04(const CEntityEvent &__eeInput);
  BOOL H0x01400005_FlyFire_05(const CEntityEvent &__eeInput);
  BOOL H0x01400006_FlyFire_06(const CEntityEvent &__eeInput);
#define  STATE_CWoman_FlyHit 0x01400007
  BOOL FlyHit(const CEntityEvent &__eeInput);
#define  STATE_CWoman_Death 0x01400008
  BOOL Death(const CEntityEvent &__eeInput);
#define  STATE_CWoman_AirToGround 0x01400009
  BOOL AirToGround(const CEntityEvent &__eeInput);
#define  STATE_CWoman_FlyOnEnemy 0x0140000a
  BOOL FlyOnEnemy(const CEntityEvent &__eeInput);
  BOOL H0x0140000b_FlyOnEnemy_01(const CEntityEvent &__eeInput);
  BOOL H0x0140000c_FlyOnEnemy_02(const CEntityEvent &__eeInput);
  BOOL H0x0140000d_FlyOnEnemy_03(const CEntityEvent &__eeInput);
  BOOL H0x0140000e_FlyOnEnemy_04(const CEntityEvent &__eeInput);
#define  STATE_CWoman_GroundFire 0x0140000f
  BOOL GroundFire(const CEntityEvent &__eeInput);
  BOOL H0x01400010_GroundFire_01(const CEntityEvent &__eeInput);
  BOOL H0x01400011_GroundFire_02(const CEntityEvent &__eeInput);
  BOOL H0x01400012_GroundFire_03(const CEntityEvent &__eeInput);
  BOOL H0x01400013_GroundFire_04(const CEntityEvent &__eeInput);
  BOOL H0x01400014_GroundFire_05(const CEntityEvent &__eeInput);
  BOOL H0x01400015_GroundFire_06(const CEntityEvent &__eeInput);
#define  STATE_CWoman_GroundHit 0x01400016
  BOOL GroundHit(const CEntityEvent &__eeInput);
  BOOL H0x01400017_GroundHit_01(const CEntityEvent &__eeInput);
  BOOL H0x01400018_GroundHit_02(const CEntityEvent &__eeInput);
  BOOL H0x01400019_GroundHit_03(const CEntityEvent &__eeInput);
  BOOL H0x0140001a_GroundHit_04(const CEntityEvent &__eeInput);
#define  STATE_CWoman_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x0140001b_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x0140001c_Main_02(const CEntityEvent &__eeInput);
};

static const char *CWoman_propnames[] = {
  "m_bKamikazeCarrier",
  "m_rKamikazeDropDistance",
  "m_bKamikazeAttached",
};
#define CWoman_propnamesct ARRAYCOUNT(CWoman_propnames)

#endif // _EntitiesV_Woman_INCLUDED
