// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.


// [Cecil] NOTE: This inline code can be included in any place that needs to retrieve properties of linked vanilla entities
// by variable name. It can be used in any project that utilizes this SDK. However, before including it, make sure to include
// <EngineEx/PropertyTables.h> header that this code relies on.

// Example: You can create a method that fills a CPropertyRefTable structure from an argument with all of the property tables
// by defining your own ENTITYPROPERTYREF_ENTRY macro as such:
//   #define ENTITYPROPERTYREF_ENTRY(Class, Refs, RefsCount) map.FillPropertyReferences(#Class, Refs, RefsCount)


#include <EccExtras/EntityProperties.h>

// Please specify your own code for this macro
#ifndef ENTITYPROPERTYREF_ENTRY
  #define ENTITYPROPERTYREF_ENTRY(Class, Refs, RefsCount)
#endif

// You can provide your own declaration specifiers using this macro
#ifndef ENTITYPROPERTYREF_DECL
  #define ENTITYPROPERTYREF_DECL static
#endif

ENTITYPROPERTYREF_DECL EntityPropertyRef CMovableBrushEntity_proprefs[] = { EntityPropertyRef() };
ENTITYPROPERTYREF_DECL const INDEX CMovableBrushEntity_proprefsct = 0;
ENTITYPROPERTYREF_ENTRY(CMovableBrushEntity, CMovableBrushEntity_proprefs, CMovableBrushEntity_proprefsct);

ENTITYPROPERTYREF_DECL EntityPropertyRef CMovableEntity_proprefs[] = {
  EntityPropertyRef("en_vDesiredTranslationRelative", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x1<<8)+1, 0, "", 0, "en_vDesiredTranslationRelative", 0, 0)),
  EntityPropertyRef("en_aDesiredRotationRelative", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ANGLE3D, NULL, (0x1<<8)+2, 0, "", 0, "en_aDesiredRotationRelative", 0, 0)),
  EntityPropertyRef("en_vCurrentTranslationAbsolute", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x1<<8)+3, 0, "", 0, "en_vCurrentTranslationAbsolute", 0, 0)),
  EntityPropertyRef("en_aCurrentRotationAbsolute", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ANGLE3D, NULL, (0x1<<8)+4, 0, "", 0, "en_aCurrentRotationAbsolute", 0, 0)),
  EntityPropertyRef("en_penReference", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x1<<8)+6, 0, "", 0, "en_penReference", 0, 0)),
  EntityPropertyRef("en_vReferencePlane", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x1<<8)+7, 0, "", 0, "en_vReferencePlane", 0, 0)),
  EntityPropertyRef("en_iReferenceSurface", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_INDEX, NULL, (0x1<<8)+8, 0, "", 0, "en_iReferenceSurface", 0, 0)),
  EntityPropertyRef("en_penLastValidReference", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x1<<8)+9, 0, "", 0, "en_penLastValidReference", 0, 0)),
  EntityPropertyRef("en_tmLastSignificantVerticalMovement", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+14, 0, "", 0, "en_tmLastSignificantVerticalMovement", 0, 0)),
  EntityPropertyRef("en_tmLastBreathed", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+10, 0, "", 0, "en_tmLastBreathed", 0, 0)),
  EntityPropertyRef("en_tmMaxHoldBreath", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+11, 0, "", 0, "en_tmMaxHoldBreath", 0, 0)),
  EntityPropertyRef("en_fDensity", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+12, 0, "", 0, "en_fDensity", 0, 0)),
  EntityPropertyRef("en_tmLastSwimDamage", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+13, 0, "", 0, "en_tmLastSwimDamage", 0, 0)),
  EntityPropertyRef("en_iUpContent", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_INDEX, NULL, (0x1<<8)+20, 0, "", 0, "en_iUpContent", 0, 0)),
  EntityPropertyRef("en_iDnContent", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_INDEX, NULL, (0x1<<8)+21, 0, "", 0, "en_iDnContent", 0, 0)),
  EntityPropertyRef("en_fImmersionFactor", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+22, 0, "", 0, "en_fImmersionFactor", 0, 0)),
  EntityPropertyRef("en_vGravityDir", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x1<<8)+25, 0, "", 0, "en_vGravityDir", 0, 0)),
  EntityPropertyRef("en_fGravityA", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+26, 0, "", 0, "en_fGravityA", 0, 0)),
  EntityPropertyRef("en_fGravityV", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+27, 0, "", 0, "en_fGravityV", 0, 0)),
  EntityPropertyRef("en_vForceDir", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x1<<8)+66, 0, "", 0, "en_vForceDir", 0, 0)),
  EntityPropertyRef("en_fForceA", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+67, 0, "", 0, "en_fForceA", 0, 0)),
  EntityPropertyRef("en_fForceV", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+68, 0, "", 0, "en_fForceV", 0, 0)),
  EntityPropertyRef("en_tmJumped", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+30, 0, "", 0, "en_tmJumped", 0, 0)),
  EntityPropertyRef("en_tmMaxJumpControl", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+31, 0, "", 0, "en_tmMaxJumpControl", 0, 0)),
  EntityPropertyRef("en_fJumpControlMultiplier", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+32, 0, "", 0, "en_fJumpControlMultiplier", 0, 0)),
  EntityPropertyRef("en_fAcceleration", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+35, 0, "", 0, "en_fAcceleration", 0, 0)),
  EntityPropertyRef("en_fDeceleration", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+36, 0, "", 0, "en_fDeceleration", 0, 0)),
  EntityPropertyRef("en_fStepUpHeight", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+37, 0, "", 0, "en_fStepUpHeight", 0, 0)),
  EntityPropertyRef("en_fStepDnHeight", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+42, 0, "", 0, "en_fStepDnHeight", 0, 0)),
  EntityPropertyRef("en_fBounceDampParallel", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+38, 0, "", 0, "en_fBounceDampParallel", 0, 0)),
  EntityPropertyRef("en_fBounceDampNormal", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+39, 0, "", 0, "en_fBounceDampNormal", 0, 0)),
  EntityPropertyRef("en_fCollisionSpeedLimit", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+40, 0, "", 0, "en_fCollisionSpeedLimit", 0, 0)),
  EntityPropertyRef("en_fCollisionDamageFactor", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x1<<8)+41, 0, "", 0, "en_fCollisionDamageFactor", 0, 0)),
  EntityPropertyRef("en_boxMovingEstimate", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOATAABBOX3D, NULL, (0x1<<8)+51, 0, "", 0, "en_boxMovingEstimate", 0, 0)),
  EntityPropertyRef("en_boxNearCached", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOATAABBOX3D, NULL, (0x1<<8)+52, 0, "", 0, "en_boxNearCached", 0, 0)),
  EntityPropertyRef("en_vIntendedTranslation", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x1<<8)+64, 0, "", 0, "en_vIntendedTranslation", 0, 0)),
  EntityPropertyRef("en_mIntendedRotation", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOATMATRIX3D, NULL, (0x1<<8)+65, 0, "", 0, "en_mIntendedRotation", 0, 0)),
};
ENTITYPROPERTYREF_DECL const INDEX CMovableEntity_proprefsct = ARRAYCOUNT(CMovableEntity_proprefs);
ENTITYPROPERTYREF_ENTRY(CMovableEntity, CMovableEntity_proprefs, CMovableEntity_proprefsct);

ENTITYPROPERTYREF_DECL EntityPropertyRef CMovableModelEntity_proprefs[] = {
  EntityPropertyRef("en_iCollisionBox", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_INDEX, NULL, (0x2<<8)+1, 0, "", 0, "en_iCollisionBox", 0, 0)),
  EntityPropertyRef("en_iWantedCollisionBox", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_INDEX, NULL, (0x2<<8)+2, 0, "", 0, "en_iWantedCollisionBox", 0, 0)),
};
ENTITYPROPERTYREF_DECL const INDEX CMovableModelEntity_proprefsct = ARRAYCOUNT(CMovableModelEntity_proprefs);
ENTITYPROPERTYREF_ENTRY(CMovableModelEntity, CMovableModelEntity_proprefs, CMovableModelEntity_proprefsct);

ENTITYPROPERTYREF_DECL EntityPropertyRef CPlayerEntity_proprefs[] = {
  EntityPropertyRef("en_tmPing", ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x4<<8)+1, 0, "", 0, "en_tmPing", 0, 0)),
};
ENTITYPROPERTYREF_DECL const INDEX CPlayerEntity_proprefsct = ARRAYCOUNT(CPlayerEntity_proprefs);
ENTITYPROPERTYREF_ENTRY(CPlayerEntity, CPlayerEntity_proprefs, CPlayerEntity_proprefsct);
