/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _Engine_Classes_BaseEvents_INCLUDED
#define _Engine_Classes_BaseEvents_INCLUDED 1
#endif // _Engine_Classes_BaseEvents_INCLUDED
