// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_AirShockwave_INCLUDED
#define _EntitiesV_AirShockwave_INCLUDED 1
#include <EntitiesV/BasicEffects.h>
#define EVENTCODE_EAirShockwave 0x015d0000
class DECL_DLL EAirShockwave : public CEntityEvent {
public:
EAirShockwave();
CEntityEvent *MakeCopy(void);
CEntityPointer penLauncher;
FLOAT fHeight;
FLOAT fEndWidth;
FLOAT fDuration;
};
DECL_DLL inline void ClearToDefault(EAirShockwave &e) { e = EAirShockwave(); } ;
extern "C" DECL_DLL CDLLEntityClass CAirShockwave_DLLClass;
class CAirShockwave : public CMovableModelEntity {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  CEntityPointer m_penLauncher;
  FLOAT m_fHeight;
  FLOAT m_fEndWidth;
  FLOAT m_tmBegin;
  FLOAT m_tmEnd;
  FLOAT m_fDuration;
  BOOL m_bGrowing;
  FLOAT m_tmLastGrow;
  FLOAT m_fFadeStartTime;
  FLOAT m_fFadeStartPercent;
  FLOAT m_fStretchY;
  FLOAT m_fBeginStretchXZ;
  FLOAT m_fEndStretchXZ;
  FLOATaabbox3D m_boxMaxSize;
  BOOL m_bFadeOut;
   CModelObject * ShockwaveModel(void);
   BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   void LaunchEntity(CEntity * pen);
   void TestForCollisionAndLaunchEntity();
#define  STATE_CAirShockwave_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x015d0001_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x015d0002_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x015d0003_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x015d0004_Main_04(const CEntityEvent &__eeInput);
  BOOL H0x015d0005_Main_05(const CEntityEvent &__eeInput);
  BOOL H0x015d0006_Main_06(const CEntityEvent &__eeInput);
};

static const char *CAirShockwave_propnames[] = {
  "m_penLauncher",
  "m_fHeight",
  "m_fEndWidth",
  "m_tmBegin",
  "m_tmEnd",
  "m_fDuration",
  "m_bGrowing",
  "m_tmLastGrow",
  "m_fFadeStartTime",
  "m_fFadeStartPercent",
  "m_fStretchY",
  "m_fBeginStretchXZ",
  "m_fEndStretchXZ",
  "m_boxMaxSize",
  "m_bFadeOut",
};
#define CAirShockwave_propnamesct ARRAYCOUNT(CAirShockwave_propnames)

#endif // _EntitiesV_AirShockwave_INCLUDED
