// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_AreaMarker_INCLUDED
#define _EntitiesV_AreaMarker_INCLUDED 1
#define CAreaMarker_ClassID 202
extern "C" DECL_DLL CDLLEntityClass CAreaMarker_DLLClass;
class CAreaMarker : public CEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  CTString m_strDescription;
  FLOATaabbox3D m_boxArea;
   void GetAreaBox(FLOATaabbox3D & box);
#define  STATE_CAreaMarker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_AreaMarker_INCLUDED
