// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#define ENTITYCLASS CCamera

CEntityProperty CCamera_properties[] = {
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+1, offsetof(CCamera, m_tmTime), "Time", 'E', "m_tmTime", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+2, offsetof(CCamera, m_fFOV), "FOV", 'F', "m_fFOV", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+5, offsetof(CCamera, m_fLastFOV), "", 0, "m_fLastFOV", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000dc<<8)+3, offsetof(CCamera, m_penTarget), "Target", 'T', "m_penTarget", C_lBLUE  | 0xFF, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_STRING, NULL, (0x000000dc<<8)+4, offsetof(CCamera, m_strName), "Name", 'N', "m_strName", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000dc<<8)+6, offsetof(CCamera, m_penOnBreak), "OnBreak", 'B', "m_penOnBreak", C_lRED  | 0xFF, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x000000dc<<8)+7, offsetof(CCamera, m_bWideScreen), "WideScreen", 'W', "m_bWideScreen", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+10, offsetof(CCamera, m_tmAtMarker), "", 0, "m_tmAtMarker", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+11, offsetof(CCamera, m_tmDelta), "", 0, "m_tmDelta", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x000000dc<<8)+13, offsetof(CCamera, m_vPNp0), "", 0, "m_vPNp0", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x000000dc<<8)+14, offsetof(CCamera, m_vPNp1), "", 0, "m_vPNp1", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x000000dc<<8)+15, offsetof(CCamera, m_vTNp0), "", 0, "m_vTNp0", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x000000dc<<8)+16, offsetof(CCamera, m_vTNp1), "", 0, "m_vTNp1", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+17, offsetof(CCamera, m_fFOVp0), "", 0, "m_fFOVp0", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+18, offsetof(CCamera, m_fFOVp1), "", 0, "m_fFOVp1", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+19, offsetof(CCamera, m_fTFOVp0), "", 0, "m_fTFOVp0", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+20, offsetof(CCamera, m_fTFOVp1), "", 0, "m_fTFOVp1", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOATQUAT3D, NULL, (0x000000dc<<8)+31, offsetof(CCamera, m_qPNp0), "", 0, "m_qPNp0", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOATQUAT3D, NULL, (0x000000dc<<8)+32, offsetof(CCamera, m_qPNp1), "", 0, "m_qPNp1", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOATQUAT3D, NULL, (0x000000dc<<8)+33, offsetof(CCamera, m_qANp0), "", 0, "m_qANp0", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOATQUAT3D, NULL, (0x000000dc<<8)+34, offsetof(CCamera, m_qANp1), "", 0, "m_qANp1", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000dc<<8)+40, offsetof(CCamera, m_penLast), "", 0, "m_penLast", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000dc<<8)+41, offsetof(CCamera, m_penPlayer), "", 0, "m_penPlayer", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_STRING, NULL, (0x000000dc<<8)+42, offsetof(CCamera, m_strDescription), "", 0, "m_strDescription", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x000000dc<<8)+43, offsetof(CCamera, m_bStopMoving), "", 0, "m_bStopMoving", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_COLOR, NULL, (0x000000dc<<8)+50, offsetof(CCamera, m_colFade0), "", 0, "m_colFade0", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_COLOR, NULL, (0x000000dc<<8)+51, offsetof(CCamera, m_colFade1), "", 0, "m_colFade1", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x000000dc<<8)+52, offsetof(CCamera, m_bMoving), "", 0, "m_bMoving", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000dc<<8)+53, offsetof(CCamera, m_penViewTarget0), "", 0, "m_penViewTarget0", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000dc<<8)+54, offsetof(CCamera, m_penViewTarget1), "", 0, "m_penViewTarget1", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x000000dc<<8)+55, offsetof(CCamera, m_vPosRatio0), "", 0, "m_vPosRatio0", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x000000dc<<8)+56, offsetof(CCamera, m_vPosRatio1), "", 0, "m_vPosRatio1", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+60, offsetof(CCamera, m_fMyTimer), "", 0, "m_fMyTimer", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+61, offsetof(CCamera, m_fMyTimerLast), "", 0, "m_fMyTimerLast", 0, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x000000dc<<8)+62, offsetof(CCamera, m_bIgnoreTimeStretch), "Ignore time stretch", 0, "m_bIgnoreTimeStretch", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x000000dc<<8)+63, offsetof(CCamera, m_bAutoRotation), "Auto rotate (AR)", 'A', "m_bAutoRotation", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+64, offsetof(CCamera, m_fStartHdg), "AR start heading", 'D', "m_fStartHdg", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+65, offsetof(CCamera, m_fRotateSpeed), "AR Rotate speed", 'S', "m_fRotateSpeed", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+66, offsetof(CCamera, m_fRotateTime), "AR Rotate time", 'I', "m_fRotateTime", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+67, offsetof(CCamera, m_fRadX), "AR Radius X", 'X', "m_fRadX", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+68, offsetof(CCamera, m_fHeight), "AR Height (controlls pitch)", 'H', "m_fHeight", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x000000dc<<8)+69, offsetof(CCamera, m_fRadZ), "AR Radius Z", 'Z', "m_fRadZ", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000000dc<<8)+70, offsetof(CCamera, m_penAutoCameraEndTarget), "Auto camera end target", 0, "m_penAutoCameraEndTarget", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ENUM, &EventEType_enum, (0x000000dc<<8)+71, offsetof(CCamera, m_eetAutoCameraEndEvent), "Auto camera end event", 0, "m_eetAutoCameraEndEvent", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT3D, NULL, (0x000000dc<<8)+72, offsetof(CCamera, m_vRelTargetOffset), "", 0, "m_vRelTargetOffset", 0, 0),
};
#define CCamera_propertiesct ARRAYCOUNT(CCamera_properties)

CEntityComponent CCamera_components[] = {
#define MODEL_CAMERA ((0x000000dc<<8)+1)
 CEntityComponent(ECT_MODEL, MODEL_CAMERA, "EFNM" "Models\\Editor\\Camera.mdl"),
#define TEXTURE_CAMERA ((0x000000dc<<8)+2)
 CEntityComponent(ECT_TEXTURE, TEXTURE_CAMERA, "EFNM" "Models\\Editor\\Camera.tex"),
};
#define CCamera_componentsct ARRAYCOUNT(CCamera_components)

CEventHandlerEntry CCamera_handlers[] = {
 {0x00dc0000, -1, CEntity::pEventHandler(&CCamera::PlayStaticCamera),DEBUGSTRING("CCamera::PlayStaticCamera")},
 {0x00dc0001, -1, CEntity::pEventHandler(&CCamera::H0x00dc0001_PlayStaticCamera_01), DEBUGSTRING("CCamera::H0x00dc0001_PlayStaticCamera_01")},
 {0x00dc0002, -1, CEntity::pEventHandler(&CCamera::H0x00dc0002_PlayStaticCamera_02), DEBUGSTRING("CCamera::H0x00dc0002_PlayStaticCamera_02")},
 {0x00dc0003, -1, CEntity::pEventHandler(&CCamera::PlayAutoRotatingCamera),DEBUGSTRING("CCamera::PlayAutoRotatingCamera")},
 {0x00dc0004, -1, CEntity::pEventHandler(&CCamera::H0x00dc0004_PlayAutoRotatingCamera_01), DEBUGSTRING("CCamera::H0x00dc0004_PlayAutoRotatingCamera_01")},
 {0x00dc0005, -1, CEntity::pEventHandler(&CCamera::H0x00dc0005_PlayAutoRotatingCamera_02), DEBUGSTRING("CCamera::H0x00dc0005_PlayAutoRotatingCamera_02")},
 {0x00dc0006, -1, CEntity::pEventHandler(&CCamera::PlayMovingCamera),DEBUGSTRING("CCamera::PlayMovingCamera")},
 {0x00dc0007, -1, CEntity::pEventHandler(&CCamera::H0x00dc0007_PlayMovingCamera_01), DEBUGSTRING("CCamera::H0x00dc0007_PlayMovingCamera_01")},
 {0x00dc0008, -1, CEntity::pEventHandler(&CCamera::H0x00dc0008_PlayMovingCamera_02), DEBUGSTRING("CCamera::H0x00dc0008_PlayMovingCamera_02")},
 {0x00dc0009, -1, CEntity::pEventHandler(&CCamera::PlayCamera),DEBUGSTRING("CCamera::PlayCamera")},
 {1, -1, CEntity::pEventHandler(&CCamera::Main),DEBUGSTRING("CCamera::Main")},
 {0x00dc000a, -1, CEntity::pEventHandler(&CCamera::H0x00dc000a_Main_01), DEBUGSTRING("CCamera::H0x00dc000a_Main_01")},
 {0x00dc000b, -1, CEntity::pEventHandler(&CCamera::H0x00dc000b_Main_02), DEBUGSTRING("CCamera::H0x00dc000b_Main_02")},
 {0x00dc000c, -1, CEntity::pEventHandler(&CCamera::H0x00dc000c_Main_03), DEBUGSTRING("CCamera::H0x00dc000c_Main_03")},
 {0x00dc000d, -1, CEntity::pEventHandler(&CCamera::H0x00dc000d_Main_04), DEBUGSTRING("CCamera::H0x00dc000d_Main_04")},
 {0x00dc000e, -1, CEntity::pEventHandler(&CCamera::H0x00dc000e_Main_05), DEBUGSTRING("CCamera::H0x00dc000e_Main_05")},
 {0x00dc000f, -1, CEntity::pEventHandler(&CCamera::H0x00dc000f_Main_06), DEBUGSTRING("CCamera::H0x00dc000f_Main_06")},
 {0x00dc0010, -1, CEntity::pEventHandler(&CCamera::H0x00dc0010_Main_07), DEBUGSTRING("CCamera::H0x00dc0010_Main_07")},
};
#define CCamera_handlersct ARRAYCOUNT(CCamera_handlers)

CEntity *CCamera_New(void) { return new CCamera; };
void CCamera_OnInitClass(void) {};
void CCamera_OnEndClass(void) {};
void CCamera_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CCamera_OnWorldEnd(CWorld *pwo) {};
void CCamera_OnWorldInit(CWorld *pwo) {};
void CCamera_OnWorldTick(CWorld *pwo) {};
void CCamera_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CCamera, CMovableModelEntity, "Camera", "Thumbnails\\Camera.tbn", 0x000000dc);
DECLARE_CTFILENAME(_fnmCCamera_tbn, "Thumbnails\\Camera.tbn");
