// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_CannonStatic_INCLUDED
#define _EntitiesV_CannonStatic_INCLUDED 1
#include <EntitiesV/ModelHolder2.h>
#include <EntitiesV/Projectile.h>
#include <EntitiesV/SoundHolder.h>
#include <EntitiesV/BloodSpray.h>
#include <EntitiesV/CannonBall.h>
extern "C" DECL_DLL CDLLEntityClass CCannonStatic_DLLClass;
class CCannonStatic : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  FLOAT m_fHealth;
  RANGE m_fFiringRangeClose;
  RANGE m_fFiringRangeFar;
  FLOAT m_fShootingPeriod;
  FLOAT m_fSize;
  FLOAT m_fMaxPitch;
  FLOAT m_fViewAngle;
  BOOL m_bActive;
  FLOAT3D m_fRotSpeedMuzzle;
  FLOAT m_fDistanceToPlayer;
  FLOAT m_fDesiredMuzzlePitch;
  INDEX m_iMuzzleDir;
  FLOAT3D m_vFiringPos;
  FLOAT3D m_vTarget;
  FLOAT3D m_aBeginMuzzleRotation;
  FLOAT3D m_aEndMuzzleRotation;
  virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
   void * GetEntityInfo(void);
  virtual const CTFileName & GetComputerMessageName(void)const;
   void Precache(void);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   INDEX AnimForDamage(FLOAT fDamage);
   INDEX AnimForDeath(void);
   BOOL IsVisible(CEntity * penEntity);
   BOOL IsInTheLineOfFire(CEntity * penEntity,FLOAT fAngle);
   CPlayer * AcquireTarget();
   void CannonBlowUp(void);
   void PreMoving();
   void PostMoving();
   BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   void UpdateAttachmentRotations(void);
   void UpdateFiringPos();
#define  STATE_CCannonStatic_MainLoop 0x01590000
  BOOL MainLoop(const CEntityEvent &__eeInput);
  BOOL H0x01590001_MainLoop_01(const CEntityEvent &__eeInput);
  BOOL H0x01590002_MainLoop_02(const CEntityEvent &__eeInput);
#define  STATE_CCannonStatic_Die 0x01590003
  BOOL Die(const CEntityEvent &__eeInput);
#define  STATE_CCannonStatic_RotateMuzzle 0x01590004
  BOOL RotateMuzzle(const CEntityEvent &__eeInput);
  BOOL H0x01590005_RotateMuzzle_01(const CEntityEvent &__eeInput);
  BOOL H0x01590006_RotateMuzzle_02(const CEntityEvent &__eeInput);
#define  STATE_CCannonStatic_FireCannon 0x01590007
  BOOL FireCannon(const CEntityEvent &__eeInput);
  BOOL H0x01590008_FireCannon_01(const CEntityEvent &__eeInput);
  BOOL H0x01590009_FireCannon_02(const CEntityEvent &__eeInput);
#define  STATE_CCannonStatic_WatchPlayers 0x0159000a
  BOOL WatchPlayers(const CEntityEvent &__eeInput);
  BOOL H0x0159000b_WatchPlayers_01(const CEntityEvent &__eeInput);
  BOOL H0x0159000c_WatchPlayers_02(const CEntityEvent &__eeInput);
  BOOL H0x0159000d_WatchPlayers_03(const CEntityEvent &__eeInput);
  BOOL H0x0159000e_WatchPlayers_04(const CEntityEvent &__eeInput);
  BOOL H0x0159000f_WatchPlayers_05(const CEntityEvent &__eeInput);
  BOOL H0x01590010_WatchPlayers_06(const CEntityEvent &__eeInput);
  BOOL H0x01590011_WatchPlayers_07(const CEntityEvent &__eeInput);
  BOOL H0x01590012_WatchPlayers_08(const CEntityEvent &__eeInput);
  BOOL H0x01590013_WatchPlayers_09(const CEntityEvent &__eeInput);
  BOOL H0x01590014_WatchPlayers_10(const CEntityEvent &__eeInput);
#define  STATE_CCannonStatic_Inactive 0x01590015
  BOOL Inactive(const CEntityEvent &__eeInput);
  BOOL H0x01590016_Inactive_01(const CEntityEvent &__eeInput);
  BOOL H0x01590017_Inactive_02(const CEntityEvent &__eeInput);
#define  STATE_CCannonStatic_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x01590018_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01590019_Main_02(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_CannonStatic_INCLUDED
