// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Catman_INCLUDED
#define _EntitiesV_Catman_INCLUDED 1
#include <EntitiesV/EnemyBase.h>
extern DECL_DLL CEntityPropertyEnumType CatmanType_enum;
enum CatmanType {
  CMT_SOLDIER = 0,
  CMT_GENERAL = 1,
  CMT_ROGUE = 2,
};
DECL_DLL inline void ClearToDefault(CatmanType &e) { e = (CatmanType)0; } ;
extern "C" DECL_DLL CDLLEntityClass CCatman_DLLClass;
class CCatman : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  enum CatmanType m_cmtType;
   void * GetEntityInfo(void);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   INDEX AnimForDamage(FLOAT fDamage);
   INDEX AnimForDeath(void);
   void DeathNotify(void);
   void StandingAnim(void);
   void WalkingAnim(void);
   void RunningAnim(void);
   void RotatingAnim(void);
   void IdleSound(void);
   void SightSound(void);
   void WoundSound(void);
   void DeathSound(void);
#define  STATE_CCatman_Fire 0x012d0000
  BOOL Fire(const CEntityEvent &__eeInput);
  BOOL H0x012d0001_Fire_01(const CEntityEvent &__eeInput);
  BOOL H0x012d0002_Fire_02(const CEntityEvent &__eeInput);
  BOOL H0x012d0003_Fire_03(const CEntityEvent &__eeInput);
  BOOL H0x012d0004_Fire_04(const CEntityEvent &__eeInput);
#define  STATE_CCatman_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};

static const char *CCatman_propnames[] = {
  "m_cmtType",
};
#define CCatman_propnamesct ARRAYCOUNT(CCatman_propnames)

#endif // _EntitiesV_Catman_INCLUDED
