// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Fireworks_INCLUDED
#define _EntitiesV_Fireworks_INCLUDED 1
extern "C" DECL_DLL CDLLEntityClass CFireworks_DLLClass;
class CFireworks : public CRationalEntity {
public:
virtual BOOL IsTargetable(void) const { return TRUE; };
virtual const CTString &GetName(void) const { return m_strName; };
  DECL_DLL virtual void SetDefaultProperties(void);
  RANGE m_rRndRadius;
  CSoundObject m_soFly;
  CSoundObject m_soExplosion;
  FLOAT m_tmActivated;
  CTString m_strName;
  FLOAT m_tmLastAnimation;
CEmiter m_emEmiter;
   void Read_t(CTStream * istr);
   void Write_t(CTStream * istr);
   void RenderParticles(void);
#define  STATE_CFireworks_SpawnFireworks 0x02680000
  BOOL SpawnFireworks(const CEntityEvent &__eeInput);
  BOOL H0x02680001_SpawnFireworks_01(const CEntityEvent &__eeInput);
  BOOL H0x02680002_SpawnFireworks_02(const CEntityEvent &__eeInput);
#define  STATE_CFireworks_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x02680003_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x02680004_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x02680005_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x02680006_Main_04(const CEntityEvent &__eeInput);
};

static const char *CFireworks_propnames[] = {
  "m_rRndRadius",
  "m_soFly",
  "m_soExplosion",
  "m_tmActivated",
  "m_strName",
  "m_tmLastAnimation",
};
#define CFireworks_propnamesct ARRAYCOUNT(CFireworks_propnames)

#endif // _EntitiesV_Fireworks_INCLUDED
