// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_GravityRouter_INCLUDED
#define _EntitiesV_GravityRouter_INCLUDED 1
#include <EntitiesV/Marker.h>
#define EVENTCODE_EChangeGravity 0x00e30000
class DECL_DLL EChangeGravity : public CEntityEvent {
public:
EChangeGravity();
CEntityEvent *MakeCopy(void);
CEntityPointer penNewGravity;
};
DECL_DLL inline void ClearToDefault(EChangeGravity &e) { e = EChangeGravity(); } ;
extern "C" DECL_DLL CDLLEntityClass CGravityRouter_DLLClass;
class CGravityRouter : public CMarker {
public:
virtual BOOL IsImportant(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
   const CTString & GetForceName(INDEX i);
   void GetForce(INDEX i,const FLOAT3D & vPoint,CForceStrength & fsGravity,CForceStrength & fsField);
   CEntity * GetForceController(INDEX iForce);
   BOOL HandleEvent(const CEntityEvent & ee);
#define  STATE_CGravityRouter_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_GravityRouter_INCLUDED
