// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_ModelHolder3_INCLUDED
#define _EntitiesV_ModelHolder3_INCLUDED 1
#include <EntitiesV/ModelDestruction.h>
#include <EntitiesV/AnimationChanger.h>
#include <EntitiesV/BloodSpray.h>
extern DECL_DLL CEntityPropertyEnumType SkaCustomShadingType_enum;
enum SkaCustomShadingType {
  SCST_NONE = 0,
  SCST_CONSTANT_SHADING = 1,
  SCST_FULL_CUSTOMIZED = 2,
};
DECL_DLL inline void ClearToDefault(SkaCustomShadingType &e) { e = (SkaCustomShadingType)0; } ;
extern DECL_DLL CEntityPropertyEnumType SkaShadowType_enum;
enum SkaShadowType {
  SST_NONE = 0,
  SST_CLUSTER = 1,
  SST_POLYGONAL = 2,
};
DECL_DLL inline void ClearToDefault(SkaShadowType &e) { e = (SkaShadowType)0; } ;
#define CModelHolder3_ClassID 242
extern "C" DECL_DLL CDLLEntityClass CModelHolder3_DLLClass;
class CModelHolder3 : public CRationalEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual const CTString &GetDescription(void) const { return m_strDescription; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTFileName m_fnModel;
  FLOAT m_fStretchAll;
  ANGLE3D m_vStretchXYZ;
  CTString m_strName;
  CTString m_strDescription;
  BOOL m_bColliding;
  enum SkaShadowType m_stClusterShadows;
  BOOL m_bBackground;
  BOOL m_bTargetable;
  enum SkaCustomShadingType m_cstCustomShading;
  ANGLE3D m_aShadingDirection;
  COLOR m_colLight;
  COLOR m_colAmbient;
  BOOL m_bActive;
  FLOAT m_fClassificationStretch;
  FLOAT m_fMaxTessellationLevel;
   BOOL FillEntityStatistics(EntityStats * pes);
   FLOAT3D GetClassificationBoxStretch(void);
   FLOAT GetMaxTessellationLevel(void);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   void * GetEntityInfo(void);
   BOOL IsTargetable(void)const;
   BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   void MirrorAndStretch(FLOAT fStretch,BOOL bMirrorX);
   void StretchModel(void);
   void InitModelHolder(void);
#define  STATE_CModelHolder3_Die 0x00f20000
  BOOL Die(const CEntityEvent &__eeInput);
#define  STATE_CModelHolder3_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x00f20001_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x00f20002_Main_02(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_ModelHolder3_INCLUDED
