// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_NavigationMarker_INCLUDED
#define _EntitiesV_NavigationMarker_INCLUDED 1
#include <EntitiesV/Marker.h>
extern "C" DECL_DLL CDLLEntityClass CNavigationMarker_DLLClass;
class DECL_DLL  CNavigationMarker : public CEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
   virtual void SetDefaultProperties(void);
  CTString m_strName;
  RANGE m_fMarkerRange;
  CEntityPointer m_penTarget0;
  CEntityPointer m_penTarget1;
  CEntityPointer m_penTarget2;
  CEntityPointer m_penTarget3;
  CEntityPointer m_penTarget4;
  CEntityPointer m_penTarget5;
CPathNode * m_ppnNode;
    CNavigationMarker(void);
     ~ CNavigationMarker(void);
   void Read_t(CTStream * istr);
   CEntity * GetTarget(void)const;
   void * GetEntityInfo(void);
   CPathNode * GetPathNode(void);
   CEntityPointer & TargetPointer(INDEX i);
   CNavigationMarker & Target(INDEX i);
   CNavigationMarker * GetLink(INDEX i);
   const CTString & GetDescription(void)const;
   BOOL MovesByTargetedRoute(CTString & strTargetProperty)const;
   BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
  virtual BOOL IsMarker(void)const;
#define  STATE_CNavigationMarker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};

static const char *CNavigationMarker_propnames[] = {
  "m_strName",
  "m_fMarkerRange",
  "m_penTarget0",
  "m_penTarget1",
  "m_penTarget2",
  "m_penTarget3",
  "m_penTarget4",
  "m_penTarget5",
};
#define CNavigationMarker_propnamesct ARRAYCOUNT(CNavigationMarker_propnames)

#endif // _EntitiesV_NavigationMarker_INCLUDED
