// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_PlayerActionMarker_INCLUDED
#define _EntitiesV_PlayerActionMarker_INCLUDED 1
#include <EntitiesV/Marker.h>
#include <EntitiesV/Player.h>
extern DECL_DLL CEntityPropertyEnumType PlayerAutoAction_enum;
enum PlayerAutoAction {
  PAA_RUN = 1,
  PAA_WAIT = 2,
  PAA_USEITEM = 3,
  PAA_STOREWEAPON = 4,
  PAA_DRAWWEAPON = 5,
  PAA_LOOKAROUND = 6,
  PAA_RUNANDSTOP = 7,
  PAA_RECORDSTATS = 8,
  PAA_ENDOFGAME = 9,
  PAA_SHOWSTATS = 10,
  PAA_APPEARING = 11,
  PAA_WAITFOREVER = 12,
  PAA_TELEPORT = 13,
  PAA_PICKITEM = 14,
  PAA_FALLDOWN = 15,
  PAA_FALLTOABYSS = 16,
  PAA_RELEASEPLAYER = 17,
  PAA_STARTCOMPUTER = 18,
  PAA_TRAVELING_IN_BEAM = 19,
  PAA_LOGO_FIRE_MINIGUN = 20,
  PAA_STARTCREDITS = 21,
  PAA_STARTINTROSCROLL = 22,
  PAA_STOPSCROLLER = 23,
  PAA_NOGRAVITY = 24,
  PAA_TURNONGRAVITY = 25,
  PAA_LOGO_FIRE_INTROSE = 26,
  PAA_INTROSE_SELECT_WEAPON = 27,
  PAA_STOPANDWAIT = 28,
};
DECL_DLL inline void ClearToDefault(PlayerAutoAction &e) { e = (PlayerAutoAction)0; } ;
extern "C" DECL_DLL CDLLEntityClass CPlayerActionMarker_DLLClass;
class CPlayerActionMarker : public CMarker {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  enum PlayerAutoAction m_paaAction;
  FLOAT m_tmWait;
  CEntityPointer m_penDoorController;
  CEntityPointer m_penTrigger;
  FLOAT m_fSpeed;
  CEntityPointer m_penItem;
   const CTString & GetDescription(void)const;
   BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
   BOOL HandleEvent(const CEntityEvent & ee);
#define  STATE_CPlayerActionMarker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};

static const char *CPlayerActionMarker_propnames[] = {
  "m_paaAction",
  "m_tmWait",
  "m_penDoorController",
  "m_penTrigger",
  "m_fSpeed",
  "m_penItem",
};
#define CPlayerActionMarker_propnamesct ARRAYCOUNT(CPlayerActionMarker_propnames)

#endif // _EntitiesV_PlayerActionMarker_INCLUDED
