// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_SummonerMarker_INCLUDED
#define _EntitiesV_SummonerMarker_INCLUDED 1
#include <EntitiesV/Marker.h>
#define CSummonerMarker_ClassID 350
extern "C" DECL_DLL CDLLEntityClass CSummonerMarker_DLLClass;
class CSummonerMarker : public CMarker {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  CTString m_strDescription;
  RANGE m_fMarkerRange;
   BOOL MovesByTargetedRoute(CTString & strTargetProperty)const;
   BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
   BOOL IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget);
#define  STATE_CSummonerMarker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_SummonerMarker_INCLUDED
