// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Water_INCLUDED
#define _EntitiesV_Water_INCLUDED 1
#include <EntitiesV/Light.h>
extern DECL_DLL CEntityPropertyEnumType WaterSize_enum;
enum WaterSize {
  WTS_SMALL = 0,
  WTS_BIG = 1,
  WTS_LARGE = 2,
};
DECL_DLL inline void ClearToDefault(WaterSize &e) { e = (WaterSize)0; } ;
#define EVENTCODE_EWater 0x01fc0000
class DECL_DLL EWater : public CEntityEvent {
public:
EWater();
CEntityEvent *MakeCopy(void);
CEntityPointer penLauncher;
enum WaterSize EwsSize;
};
DECL_DLL inline void ClearToDefault(EWater &e) { e = EWater(); } ;
extern "C" DECL_DLL CDLLEntityClass CWater_DLLClass;
class CWater : public CMovableModelEntity {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  CEntityPointer m_penLauncher;
  enum WaterSize m_EwsSize;
  FLOAT m_fDamageAmount;
  FLOAT m_fIgnoreTime;
  FLOAT m_fPushAwayFactor;
CLightSource m_lsLightSource;
   void Read_t(CTStream * istr);
   CLightSource * GetLightSource(void);
   void SetupLightSource(void);
   void RenderParticles(void);
   void WaterTouch(CEntityPointer penHit);
#define  STATE_CWater_WaterFly 0x01fc0001
  BOOL WaterFly(const CEntityEvent &__eeInput);
  BOOL H0x01fc0002_WaterFly_01(const CEntityEvent &__eeInput);
  BOOL H0x01fc0003_WaterFly_02(const CEntityEvent &__eeInput);
#define  STATE_CWater_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x01fc0004_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01fc0005_Main_02(const CEntityEvent &__eeInput);
};

static const char *CWater_propnames[] = {
  "m_penLauncher",
  "m_EwsSize",
  "m_fDamageAmount",
  "m_fIgnoreTime",
  "m_fPushAwayFactor",
};
#define CWater_propnamesct ARRAYCOUNT(CWater_propnames)

#endif // _EntitiesV_Water_INCLUDED
