// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_BigHead_INCLUDED
#define _EntitiesV_BigHead_INCLUDED 1
#include <EntitiesV/EnemyBase.h>
#include <EntitiesV/BasicEffects.h>
extern DECL_DLL CEntityPropertyEnumType BigHeadType_enum;
enum BigHeadType {
  BHT_NORMAL = 0,
  BHT_ZOMBIE = 1,
  BHT_SAINT = 2,
};
DECL_DLL inline void ClearToDefault(BigHeadType &e) { e = (BigHeadType)0; } ;
#define CBigHead_ClassID 340
extern "C" DECL_DLL CDLLEntityClass CBigHead_DLLClass;
class CBigHead : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  CTFileName m_fnmHeadTex;
  CTFileName m_fnmNameSnd;
  FLOAT m_tmLastGreetTime;
  enum BigHeadType m_bhtType;
  BOOL m_bIgnorePlayer;
  BOOL m_bPlayingWalkSound;
  BOOL m_bSleeping;
  FLOAT m_tmLastWalkingSoundTime;
  FLOAT m_tmWalkingSound;
CAutoPrecacheSound m_aps;
CAutoPrecacheTexture m_apt;
   BOOL HandleEvent(const CEntityEvent & ee);
   void * GetEntityInfo(void);
   void Precache(void);
   INDEX GetWalkAnim(void);
   INDEX AnimForDamage(FLOAT fDamage);
   INDEX AnimForDeath(void);
   void DeathNotify(void);
   void StandingAnim(void);
   void WalkingAnim(void);
   void RunningAnim(void);
   void RotatingAnim(void);
   void PlayWalkSound(void);
   void IdleSound(void);
   void SightSound(void);
   void WoundSound(void);
   void DeathSound(void);
#define  STATE_CBigHead_Fire 0x01540000
  BOOL Fire(const CEntityEvent &__eeInput);
  BOOL H0x01540001_Fire_01(const CEntityEvent &__eeInput);
  BOOL H0x01540002_Fire_02(const CEntityEvent &__eeInput);
  BOOL H0x01540003_Fire_03(const CEntityEvent &__eeInput);
#define  STATE_CBigHead_Sleep 0x01540004
  BOOL Sleep(const CEntityEvent &__eeInput);
  BOOL H0x01540005_Sleep_01(const CEntityEvent &__eeInput);
  BOOL H0x01540006_Sleep_02(const CEntityEvent &__eeInput);
#define  STATE_CBigHead_WakeUp 0x01540007
  BOOL WakeUp(const CEntityEvent &__eeInput);
  BOOL H0x01540008_WakeUp_01(const CEntityEvent &__eeInput);
  BOOL H0x01540009_WakeUp_02(const CEntityEvent &__eeInput);
#define  STATE_CBigHead_PreMainLoop 0x0154000a
  BOOL PreMainLoop(const CEntityEvent &__eeInput);
  BOOL H0x0154000b_PreMainLoop_01(const CEntityEvent &__eeInput);
  BOOL H0x0154000c_PreMainLoop_02(const CEntityEvent &__eeInput);
  BOOL H0x0154000d_PreMainLoop_03(const CEntityEvent &__eeInput);
#define  STATE_CBigHead_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_BigHead_INCLUDED
