// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Demon_INCLUDED
#define _EntitiesV_Demon_INCLUDED 1
#include <EntitiesV/EnemyBase.h>
#include <EntitiesV/BasicEffects.h>
#define CDemon_ClassID 336
extern "C" DECL_DLL CDLLEntityClass CDemon_DLLClass;
class CDemon : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  INDEX m_iCounter;
  CEntityPointer m_penFireFX;
   BOOL HandleEvent(const CEntityEvent & ee);
  virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
  virtual const CTFileName & GetComputerMessageName(void)const;
   void Precache(void);
   void * GetEntityInfo(void);
   BOOL ForcesCannonballToExplode(void);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   INDEX AnimForDamage(FLOAT fDamage);
   INDEX AnimForDeath(void);
   FLOAT WaitForDust(FLOAT3D & vStretch);
   void DeathNotify(void);
   void StandingAnim(void);
   void WalkingAnim(void);
   void RunningAnim(void);
   void RotatingAnim(void);
   void IdleSound(void);
   void SightSound(void);
   void WoundSound(void);
   void DeathSound(void);
   void EnemyPostInit(void);
#define  STATE_CDemon_Fire 0x01500000
  BOOL Fire(const CEntityEvent &__eeInput);
  BOOL H0x01500001_Fire_01(const CEntityEvent &__eeInput);
  BOOL H0x01500002_Fire_02(const CEntityEvent &__eeInput);
  BOOL H0x01500003_Fire_03(const CEntityEvent &__eeInput);
  BOOL H0x01500004_Fire_04(const CEntityEvent &__eeInput);
  BOOL H0x01500005_Fire_05(const CEntityEvent &__eeInput);
  BOOL H0x01500006_Fire_06(const CEntityEvent &__eeInput);
  BOOL H0x01500007_Fire_07(const CEntityEvent &__eeInput);
  BOOL H0x01500008_Fire_08(const CEntityEvent &__eeInput);
  BOOL H0x01500009_Fire_09(const CEntityEvent &__eeInput);
  BOOL H0x0150000a_Fire_10(const CEntityEvent &__eeInput);
#define  STATE_CDemon_Hit 0x0150000b
  BOOL Hit(const CEntityEvent &__eeInput);
  BOOL H0x0150000c_Hit_01(const CEntityEvent &__eeInput);
  BOOL H0x0150000d_Hit_02(const CEntityEvent &__eeInput);
  BOOL H0x0150000e_Hit_03(const CEntityEvent &__eeInput);
  BOOL H0x0150000f_Hit_04(const CEntityEvent &__eeInput);
  BOOL H0x01500010_Hit_05(const CEntityEvent &__eeInput);
  BOOL H0x01500011_Hit_06(const CEntityEvent &__eeInput);
#define  STATE_CDemon_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_Demon_INCLUDED
