// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#define ENTITYCLASS CEnvironmentMarker

CEntityProperty CEnvironmentMarker_properties[] = {
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000385<<8)+1, offsetof(CEnvironmentMarker, m_fWaitTime), "Wait time", 'W', "m_fWaitTime", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000385<<8)+2, offsetof(CEnvironmentMarker, m_fRandomTime), "Random time", 'E', "m_fRandomTime", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_RANGE, NULL, (0x00000385<<8)+3, offsetof(CEnvironmentMarker, m_fMarkerRange), "Marker range", 'R', "m_fMarkerRange", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x00000385<<8)+4, offsetof(CEnvironmentMarker, m_bFixedAnimLength), "Fixed anim length", 'F', "m_bFixedAnimLength", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_BOOL, NULL, (0x00000385<<8)+5, offsetof(CEnvironmentMarker, m_bChangeDefaultAnim), "Change default anim", 'C', "m_bChangeDefaultAnim", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000385<<8)+6, offsetof(CEnvironmentMarker, m_fMoveSpeed), "Move speed", 'V', "m_fMoveSpeed", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FLOAT, NULL, (0x00000385<<8)+7, offsetof(CEnvironmentMarker, m_fRotateSpeed), "Rotate speed", 'B', "m_fRotateSpeed", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_FILENAME, NULL, (0x00000385<<8)+20, offsetof(CEnvironmentMarker, m_fnMdl), "Model", 'M', "m_fnMdl", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_ANIMATION, NULL, (0x00000385<<8)+21, offsetof(CEnvironmentMarker, m_iAnim), "Animation", 'A', "m_iAnim", 0x7F0000FFUL, 0),
 ENGINE_SPECIFIC_PROP_DEF(CEntityProperty::EPT_MODELOBJECT, NULL, (0x00000385<<8)+22, offsetof(CEnvironmentMarker, m_moAnimData), "", 0, "m_moAnimData", 0, 0),
};
#define CEnvironmentMarker_propertiesct ARRAYCOUNT(CEnvironmentMarker_properties)

CEntityComponent CEnvironmentMarker_components[] = {
#define MODEL_MARKER ((0x00000385<<8)+1)
 CEntityComponent(ECT_MODEL, MODEL_MARKER, "EFNM" "Models\\Editor\\EnvironmentMarker.mdl"),
#define TEXTURE_MARKER ((0x00000385<<8)+2)
 CEntityComponent(ECT_TEXTURE, TEXTURE_MARKER, "EFNM" "Models\\Editor\\EnvironmentMarker.tex"),
};
#define CEnvironmentMarker_componentsct ARRAYCOUNT(CEnvironmentMarker_components)

CEventHandlerEntry CEnvironmentMarker_handlers[] = {
 {1, -1, CEntity::pEventHandler(&CEnvironmentMarker::Main),DEBUGSTRING("CEnvironmentMarker::Main")},
};
#define CEnvironmentMarker_handlersct ARRAYCOUNT(CEnvironmentMarker_handlers)

CEntity *CEnvironmentMarker_New(void) { return new CEnvironmentMarker; };
void CEnvironmentMarker_OnInitClass(void) {};
void CEnvironmentMarker_OnEndClass(void) {};
void CEnvironmentMarker_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CEnvironmentMarker_OnWorldEnd(CWorld *pwo) {};
void CEnvironmentMarker_OnWorldInit(CWorld *pwo) {};
void CEnvironmentMarker_OnWorldTick(CWorld *pwo) {};
void CEnvironmentMarker_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CEnvironmentMarker, CMarker, "Environment Marker", "Thumbnails\\EnvironmentMarker.tbn", 0x00000385);
DECLARE_CTFILENAME(_fnmCEnvironmentMarker_tbn, "Thumbnails\\EnvironmentMarker.tbn");
