// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_ExotechLarvaBattery_INCLUDED
#define _EntitiesV_ExotechLarvaBattery_INCLUDED 1
#include <EntitiesV/BloodSpray.h>
#include <EntitiesV/Projectile.h>
#define CExotechLarvaBattery_ClassID 351
extern "C" DECL_DLL CDLLEntityClass CExotechLarvaBattery_DLLClass;
class CExotechLarvaBattery : public CRationalEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  BOOL m_bActive;
  FLOAT m_fMaxHealth;
  FLOAT m_fStretch;
  FLOAT m_fBurnTreshold;
  CEntityPointer m_penSpray;
  FLOAT m_tmSpraySpawned;
  CTString m_strName;
  BOOL m_bCustomShading;
  ANGLE3D m_aShadingDirection;
  COLOR m_colLight;
  COLOR m_colAmbient;
  CSoundObject m_soSound;
   void Precache(void);
   BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   void RenderParticles(void);
   void SpawnExplosions(void);
   void AddAttachments(void);
   void RemoveAttachment(INDEX iAtt);
#define  STATE_CExotechLarvaBattery_Destroyed 0x015f0000
  BOOL Destroyed(const CEntityEvent &__eeInput);
  BOOL H0x015f0001_Destroyed_01(const CEntityEvent &__eeInput);
  BOOL H0x015f0002_Destroyed_02(const CEntityEvent &__eeInput);
  BOOL H0x015f0003_Destroyed_03(const CEntityEvent &__eeInput);
  BOOL H0x015f0004_Destroyed_04(const CEntityEvent &__eeInput);
#define  STATE_CExotechLarvaBattery_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x015f0005_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x015f0006_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x015f0007_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x015f0008_Main_04(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_ExotechLarvaBattery_INCLUDED
