// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_ScrollHolder_INCLUDED
#define _EntitiesV_ScrollHolder_INCLUDED 1
#define CScrollHolder_ClassID 238
extern "C" DECL_DLL CDLLEntityClass CScrollHolder_DLLClass;
class CScrollHolder : public CRationalEntity {
public:
virtual BOOL IsTargetable(void) const { return TRUE; };
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsImportant(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  CTString m_strDescription;
  CTFileName m_fnmMessage;
  FLOAT m_fMyTimer;
  FLOAT m_fMyTimerLast;
  FLOAT m_fSpeed;
  CEntityPointer m_penEndCreditsTrigger;
  BOOL m_bDataError;
BOOL bDataLoaded;
   const CTString & GetDescription(void)const;
    CScrollHolder(void);
   BOOL ReloadData(void);
   BOOL LoadOneFile(const CTFileName & fnm);
   BOOL Credits_On(CTFileName fnScrollText);
   void Credits_Off(void);
   FLOAT Credits_Render(CScrollHolder * penThis,CDrawPort * pdp);
#define  STATE_CScrollHolder_WaitScrollingToEnd 0x00ee0000
  BOOL WaitScrollingToEnd(const CEntityEvent &__eeInput);
  BOOL H0x00ee0001_WaitScrollingToEnd_01(const CEntityEvent &__eeInput);
  BOOL H0x00ee0002_WaitScrollingToEnd_02(const CEntityEvent &__eeInput);
  BOOL H0x00ee0003_WaitScrollingToEnd_03(const CEntityEvent &__eeInput);
  BOOL H0x00ee0004_WaitScrollingToEnd_04(const CEntityEvent &__eeInput);
#define  STATE_CScrollHolder_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x00ee0005_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x00ee0006_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x00ee0007_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x00ee0008_Main_04(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_ScrollHolder_INCLUDED
