// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Terrain_INCLUDED
#define _EntitiesV_Terrain_INCLUDED 1
#define CTerrainEntity_ClassID 108
extern "C" DECL_DLL CDLLEntityClass CTerrainEntity_DLLClass;
class CTerrainEntity : public CEntity {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
#define  STATE_CTerrainEntity_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_Terrain_INCLUDED
