// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_CannonRotating_INCLUDED
#define _EntitiesV_CannonRotating_INCLUDED 1
#include <EntitiesV/ModelHolder2.h>
#include <EntitiesV/Projectile.h>
#include <EntitiesV/SoundHolder.h>
#include <EntitiesV/BloodSpray.h>
#include <EntitiesV/CannonBall.h>
#define CCannonRotating_ClassID 345
extern "C" DECL_DLL CDLLEntityClass CCannonRotating_DLLClass;
class CCannonRotating : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  FLOAT m_fHealth;
  RANGE m_fFiringRangeClose;
  RANGE m_fFiringRangeFar;
  FLOAT m_fWaitAfterFire;
  FLOAT m_fSize;
  FLOAT m_fMaxPitch;
  FLOAT m_fViewAngle;
  FLOAT m_fScanAngle;
  FLOAT m_fRotationSpeed;
  BOOL m_bActive;
  FLOAT3D m_fRotSpeedMuzzle;
  FLOAT3D m_fRotSpeedRotator;
  FLOAT m_fDistanceToPlayer;
  FLOAT m_fDesiredMuzzlePitch;
  FLOAT m_iMuzzleDir;
  FLOAT3D m_vFiringPos;
  FLOAT3D m_vTarget;
  FLOAT m_tmLastFireTime;
  FLOAT3D m_aBeginMuzzleRotation;
  FLOAT3D m_aEndMuzzleRotation;
  FLOAT3D m_aBeginRotatorRotation;
  FLOAT3D m_aEndRotatorRotation;
  virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
   void * GetEntityInfo(void);
  virtual const CTFileName & GetComputerMessageName(void)const;
   void Precache(void);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   INDEX AnimForDamage(FLOAT fDamage);
   INDEX AnimForDeath(void);
   BOOL IsVisible(CEntity * penEntity);
   BOOL IsInTheLineOfFire(CEntity * penEntity,FLOAT fAngle);
   CPlayer * AcquireTarget();
   void CannonBlowUp(void);
   void PreMoving();
   void PostMoving();
   BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   void UpdateAttachmentRotations(void);
   void UpdateFiringPos();
#define  STATE_CCannonRotating_MainLoop 0x01590000
  BOOL MainLoop(const CEntityEvent &__eeInput);
  BOOL H0x01590001_MainLoop_01(const CEntityEvent &__eeInput);
  BOOL H0x01590002_MainLoop_02(const CEntityEvent &__eeInput);
#define  STATE_CCannonRotating_Scan 0x01590003
  BOOL Scan(const CEntityEvent &__eeInput);
  BOOL H0x01590004_Scan_01(const CEntityEvent &__eeInput);
  BOOL H0x01590005_Scan_02(const CEntityEvent &__eeInput);
  BOOL H0x01590006_Scan_03(const CEntityEvent &__eeInput);
  BOOL H0x01590007_Scan_04(const CEntityEvent &__eeInput);
  BOOL H0x01590008_Scan_05(const CEntityEvent &__eeInput);
  BOOL H0x01590009_Scan_06(const CEntityEvent &__eeInput);
  BOOL H0x0159000a_Scan_07(const CEntityEvent &__eeInput);
  BOOL H0x0159000b_Scan_08(const CEntityEvent &__eeInput);
  BOOL H0x0159000c_Scan_09(const CEntityEvent &__eeInput);
  BOOL H0x0159000d_Scan_10(const CEntityEvent &__eeInput);
  BOOL H0x0159000e_Scan_11(const CEntityEvent &__eeInput);
  BOOL H0x0159000f_Scan_12(const CEntityEvent &__eeInput);
#define  STATE_CCannonRotating_Die 0x01590010
  BOOL Die(const CEntityEvent &__eeInput);
#define  STATE_CCannonRotating_RotateMuzzle 0x01590011
  BOOL RotateMuzzle(const CEntityEvent &__eeInput);
  BOOL H0x01590012_RotateMuzzle_01(const CEntityEvent &__eeInput);
  BOOL H0x01590013_RotateMuzzle_02(const CEntityEvent &__eeInput);
#define  STATE_CCannonRotating_FireCannon 0x01590014
  BOOL FireCannon(const CEntityEvent &__eeInput);
  BOOL H0x01590015_FireCannon_01(const CEntityEvent &__eeInput);
  BOOL H0x01590016_FireCannon_02(const CEntityEvent &__eeInput);
#define  STATE_CCannonRotating_Inactive 0x01590017
  BOOL Inactive(const CEntityEvent &__eeInput);
  BOOL H0x01590018_Inactive_01(const CEntityEvent &__eeInput);
  BOOL H0x01590019_Inactive_02(const CEntityEvent &__eeInput);
#define  STATE_CCannonRotating_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x0159001a_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x0159001b_Main_02(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_CannonRotating_INCLUDED
