// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_EnemyDive_INCLUDED
#define _EntitiesV_EnemyDive_INCLUDED 1
#include <EntitiesV/EnemyBase.h>
#include <EntitiesV/Debris.h>
#include <EntitiesV/EnemyMarker.h>
extern DECL_DLL CEntityPropertyEnumType EnemyDiveType_enum;
enum EnemyDiveType {
  EDT_GROUND_ONLY = 0,
  EDT_DIVE_ONLY = 1,
  EDT_GROUND_DIVE = 2,
};
DECL_DLL inline void ClearToDefault(EnemyDiveType &e) { e = (EnemyDiveType)0; } ;
#define CEnemyDive_ClassID 313
extern "C" DECL_DLL CDLLEntityClass CEnemyDive_DLLClass;
class DECL_DLL  CEnemyDive : public CEnemyBase {
public:
   virtual void SetDefaultProperties(void);
  enum EnemyDiveType m_EedtType;
  BOOL m_bInLiquid;
  FLOAT m_fDiveWalkSpeed;
  ANGLE m_aDiveWalkRotateSpeed;
  FLOAT m_fDiveAttackRunSpeed;
  ANGLE m_aDiveAttackRotateSpeed;
  FLOAT m_fDiveCloseRunSpeed;
  ANGLE m_aDiveCloseRotateSpeed;
  FLOAT m_fDiveAttackDistance;
  FLOAT m_fDiveCloseDistance;
  FLOAT m_fDiveAttackFireTime;
  FLOAT m_fDiveCloseFireTime;
  FLOAT m_fDiveStopDistance;
  FLOAT m_fDiveIgnoreRange;
  FLOAT m_fDiveLockOnEnemyTime;
  virtual FLOAT & GetProp(FLOAT & m_fBase);
   void StartPathFinding(void);
  virtual void AdjustDifficulty(void);
  virtual BOOL CanHitEnemy(CEntity * penTarget,FLOAT fCosAngle);
   void PostMoving(void);
  virtual ULONG SetDesiredMovement(void);
   BOOL MayMoveToAttack(void);
   void SetEntityPosition();
  virtual void ChangeCollisionToLiquid(void);
  virtual void ChangeCollisionToGround(void);
#define  STATE_CEnemyDive_Hit 0x01390000
  BOOL Hit(const CEntityEvent &__eeInput);
#define  STATE_CEnemyDive_Fire 0x01390001
  BOOL Fire(const CEntityEvent &__eeInput);
#define  STATE_CEnemyDive_MainLoop 0x01390002
  BOOL MainLoop(const CEntityEvent &__eeInput);
#define  STATE_CEnemyDive_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
#define  STATE_CEnemyDive_GroundHit 0x01390003
  BOOL GroundHit(const CEntityEvent &__eeInput);
#define  STATE_CEnemyDive_GroundFire 0x01390004
  BOOL GroundFire(const CEntityEvent &__eeInput);
#define  STATE_CEnemyDive_DiveHit 0x01390005
  BOOL DiveHit(const CEntityEvent &__eeInput);
#define  STATE_CEnemyDive_DiveFire 0x01390006
  BOOL DiveFire(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_EnemyDive_INCLUDED
