// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_GravityMarker_INCLUDED
#define _EntitiesV_GravityMarker_INCLUDED 1
#include <EntitiesV/Marker.h>
#include <EntitiesV/GravityRouter.h>
extern DECL_DLL CEntityPropertyEnumType GravityType_enum;
enum GravityType {
  LT_PARALLEL = 0,
  LT_CENTRAL = 1,
  LT_CYLINDRICAL = 2,
  LT_TORUS = 3,
};
DECL_DLL inline void ClearToDefault(GravityType &e) { e = (GravityType)0; } ;
extern "C" DECL_DLL CDLLEntityClass CGravityMarker_DLLClass;
class CGravityMarker : public CMarker {
public:
virtual BOOL IsImportant(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  enum GravityType m_gtType;
  FLOAT m_fStrength;
  RANGE m_rFallOff;
  RANGE m_rHotSpot;
  RANGE m_rTorusR;
  FLOAT m_fAcc;
  FLOAT m_fSign;
  FLOAT m_fStep;
  ANGLE3D m_aForceDir;
  FLOAT m_fForceA;
  FLOAT m_fForceV;
  FLOAT3D m_vForceDir;
  inline FLOAT StrengthAtDistance(FLOAT fDistance) {FLOAT fStrength  = (m_rFallOff  - fDistance ) * m_fStep ;return Clamp  (fStrength  , 0.0f , m_fAcc );};
   const CTString & GetForceName(INDEX i);
   void GetForce(INDEX i,const FLOAT3D & vPoint,CForceStrength & fsGravity,CForceStrength & fsField);
   BOOL HandleEvent(const CEntityEvent & ee);
#define  STATE_CGravityMarker_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_GravityMarker_INCLUDED
