// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_Summoner_INCLUDED
#define _EntitiesV_Summoner_INCLUDED 1
#include <EntitiesV/EnemyBase.h>
#include <EntitiesV/SpawnerProjectile.h>
#include <EntitiesV/AreaMarker.h>
#include <EntitiesV/SummonerMarker.h>
#include <EntitiesV/Player.h>
#define EVENTCODE_ESummonerTeleport 0x015b0000
class DECL_DLL ESummonerTeleport : public CEntityEvent {
public:
ESummonerTeleport();
CEntityEvent *MakeCopy(void);
FLOAT fWait;
};
DECL_DLL inline void ClearToDefault(ESummonerTeleport &e) { e = ESummonerTeleport(); } ;
#define CSummoner_ClassID 347
extern "C" DECL_DLL CDLLEntityClass CSummoner_DLLClass;
class CSummoner : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  BOOL m_bInvulnerable;
  CEntityPointer m_penBeginDeathTarget;
  CEntityPointer m_penEndDeathTarget;
  CEntityPointer m_penExplodeDeathTarget;
  BOOL m_bShouldTeleport;
  FLOAT m_fFirePeriod;
  FLOAT m_fImmaterialDuration;
  FLOAT m_fCorporealDuration;
  FLOAT m_tmMaterializationTime;
  FLOAT m_fStretch;
  INDEX m_iSize;
  CEntityPointer m_penControlArea;
  INDEX m_iGroup01Count;
  CEntityPointer m_penGroup01Template01;
  CEntityPointer m_penGroup01Template02;
  CEntityPointer m_penGroup01Template03;
  CEntityPointer m_penGroup01Template04;
  CEntityPointer m_penGroup01Template05;
  CEntityPointer m_penGroup01Template06;
  INDEX m_iGroup02Count;
  CEntityPointer m_penGroup02Template01;
  CEntityPointer m_penGroup02Template02;
  CEntityPointer m_penGroup02Template03;
  CEntityPointer m_penGroup02Template04;
  CEntityPointer m_penGroup02Template05;
  CEntityPointer m_penGroup02Template06;
  INDEX m_iGroup03Count;
  CEntityPointer m_penGroup03Template01;
  CEntityPointer m_penGroup03Template02;
  CEntityPointer m_penGroup03Template03;
  CEntityPointer m_penGroup03Template04;
  CEntityPointer m_penGroup03Template05;
  CEntityPointer m_penGroup03Template06;
  CEntityPointer m_penTeleportMarker;
  INDEX m_iTeleportMarkers;
  CEntityPointer m_penSpawnMarker;
  INDEX m_iSpawnMarkers;
  FLOAT m_fTeleportWaitTime;
  FLOAT m_fFuss;
  INDEX m_iEnemyCount;
  FLOAT m_fMaxCurrentFuss;
  FLOAT m_fMaxBeginFuss;
  FLOAT m_fMaxEndFuss;
  INDEX m_iSpawnScheme;
  BOOL m_bFireOK;
  BOOL m_bFiredThisTurn;
  FLOAT m_fDamageSinceLastSpawn;
  BOOL m_bExploded;
  BOOL m_bDying;
  FLOAT m_tmDeathBegin;
  FLOAT m_fDeathDuration;
  CEntityPointer m_penDeathInflictor;
  CEntityPointer m_penKiller;
  FLOAT3D m_vDeathPosition;
  CEntityPointer m_penDeathMarker;
  INDEX m_iIndex;
  INDEX m_iTaunt;
  FLOAT m_tmParticlesDisappearStart;
  FLOAT m_tmLastAnimation;
  CSoundObject m_soExplosion;
  CSoundObject m_soSound;
  CSoundObject m_soChant;
  CSoundObject m_soTeleport;
CEmiter m_emEmiter;
   void Read_t(CTStream * istr);
   void Write_t(CTStream * istr);
   BOOL IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget);
   BOOL DoSafetyChecks(void);
  virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
  virtual const CTFileName & GetComputerMessageName(void)const;
   void Precache(void);
   void * GetEntityInfo(void);
   CMusicHolder * GetMusicHolder();
   BOOL DistanceToAllPlayersGreaterThen(FLOAT fDistance);
   void ShakeItBaby(FLOAT tmShaketime,FLOAT fPower,BOOL bFadeIn);
   void ChangeEnemyNumberForAllPlayers(INDEX iDelta);
   void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   void StandingAnimFight(void);
   void StandingAnim(void);
   void WalkingAnim(void);
   void RunningAnim(void);
   void RotatingAnim(void);
   void IdleSound(void);
   FLOAT3D AcquireTarget();
   void LaunchMonster(FLOAT3D vTarget,CEntity * penTemplate);
   FLOAT FussModifier(INDEX iEnemyCount);
   void RecalculateFuss(void);
   void CountEnemiesAndScoreValue(INDEX & iEnemies,FLOAT & fScore);
   CEnemyBase * GetRandomTemplate(INDEX iGroup);
   void DisappearEffect(void);
   void SpawnTeleportEffect(void);
   void KillAllEnemiesInArea(EDeath eDeath);
   void RenderParticles(void);
#define  STATE_CSummoner_InitiateTeleport 0x015b0001
  BOOL InitiateTeleport(const CEntityEvent &__eeInput);
  BOOL H0x015b0002_InitiateTeleport_01(const CEntityEvent &__eeInput);
  BOOL H0x015b0003_InitiateTeleport_02(const CEntityEvent &__eeInput);
#define  STATE_CSummoner_Fire 0x015b0004
  BOOL Fire(const CEntityEvent &__eeInput);
  BOOL H0x015b0005_Fire_01(const CEntityEvent &__eeInput);
  BOOL H0x015b0006_Fire_02(const CEntityEvent &__eeInput);
  BOOL H0x015b0007_Fire_03(const CEntityEvent &__eeInput);
  BOOL H0x015b0008_Fire_04(const CEntityEvent &__eeInput);
  BOOL H0x015b0009_Fire_05(const CEntityEvent &__eeInput);
  BOOL H0x015b000a_Fire_06(const CEntityEvent &__eeInput);
  BOOL H0x015b000b_Fire_07(const CEntityEvent &__eeInput);
  BOOL H0x015b000c_Fire_08(const CEntityEvent &__eeInput);
  BOOL H0x015b000d_Fire_09(const CEntityEvent &__eeInput);
  BOOL H0x015b000e_Fire_10(const CEntityEvent &__eeInput);
  BOOL H0x015b000f_Fire_11(const CEntityEvent &__eeInput);
  BOOL H0x015b0010_Fire_12(const CEntityEvent &__eeInput);
  BOOL H0x015b0011_Fire_13(const CEntityEvent &__eeInput);
  BOOL H0x015b0012_Fire_14(const CEntityEvent &__eeInput);
#define  STATE_CSummoner_Hit 0x015b0013
  BOOL Hit(const CEntityEvent &__eeInput);
#define  STATE_CSummoner_Die 0x015b0014
  BOOL Die(const CEntityEvent &__eeInput);
  BOOL H0x015b0015_Die_01(const CEntityEvent &__eeInput);
  BOOL H0x015b0016_Die_02(const CEntityEvent &__eeInput);
  BOOL H0x015b0017_Die_03(const CEntityEvent &__eeInput);
  BOOL H0x015b0018_Die_04(const CEntityEvent &__eeInput);
  BOOL H0x015b0019_Die_05(const CEntityEvent &__eeInput);
  BOOL H0x015b001a_Die_06(const CEntityEvent &__eeInput);
  BOOL H0x015b001b_Die_07(const CEntityEvent &__eeInput);
  BOOL H0x015b001c_Die_08(const CEntityEvent &__eeInput);
  BOOL H0x015b001d_Die_09(const CEntityEvent &__eeInput);
  BOOL H0x015b001e_Die_10(const CEntityEvent &__eeInput);
  BOOL H0x015b001f_Die_11(const CEntityEvent &__eeInput);
  BOOL H0x015b0020_Die_12(const CEntityEvent &__eeInput);
#define  STATE_CSummoner_TeleportToDeathMarker 0x015b0021
  BOOL TeleportToDeathMarker(const CEntityEvent &__eeInput);
  BOOL H0x015b0022_TeleportToDeathMarker_01(const CEntityEvent &__eeInput);
  BOOL H0x015b0023_TeleportToDeathMarker_02(const CEntityEvent &__eeInput);
  BOOL H0x015b0024_TeleportToDeathMarker_03(const CEntityEvent &__eeInput);
  BOOL H0x015b0025_TeleportToDeathMarker_04(const CEntityEvent &__eeInput);
  BOOL H0x015b0026_TeleportToDeathMarker_05(const CEntityEvent &__eeInput);
  BOOL H0x015b0027_TeleportToDeathMarker_06(const CEntityEvent &__eeInput);
  BOOL H0x015b0028_TeleportToDeathMarker_07(const CEntityEvent &__eeInput);
  BOOL H0x015b0029_TeleportToDeathMarker_08(const CEntityEvent &__eeInput);
#define  STATE_CSummoner_BossAppear 0x015b002a
  BOOL BossAppear(const CEntityEvent &__eeInput);
#define  STATE_CSummoner_PreMainLoop 0x015b002b
  BOOL PreMainLoop(const CEntityEvent &__eeInput);
  BOOL H0x015b002c_PreMainLoop_01(const CEntityEvent &__eeInput);
  BOOL H0x015b002d_PreMainLoop_02(const CEntityEvent &__eeInput);
#define  STATE_CSummoner_Immaterial 0x015b002e
  BOOL Immaterial(const CEntityEvent &__eeInput);
  BOOL H0x015b002f_Immaterial_01(const CEntityEvent &__eeInput);
  BOOL H0x015b0030_Immaterial_02(const CEntityEvent &__eeInput);
  BOOL H0x015b0031_Immaterial_03(const CEntityEvent &__eeInput);
  BOOL H0x015b0032_Immaterial_04(const CEntityEvent &__eeInput);
#define  STATE_CSummoner_SummonerLoop 0x015b0033
  BOOL SummonerLoop(const CEntityEvent &__eeInput);
  BOOL H0x015b0034_SummonerLoop_01(const CEntityEvent &__eeInput);
  BOOL H0x015b0035_SummonerLoop_02(const CEntityEvent &__eeInput);
#define  STATE_CSummoner_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x015b0036_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x015b0037_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x015b0038_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x015b0039_Main_04(const CEntityEvent &__eeInput);
  BOOL H0x015b003a_Main_05(const CEntityEvent &__eeInput);
  BOOL H0x015b003b_Main_06(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_Summoner_INCLUDED
