// This file is generated by Entity Class Compiler, (c) 2002-2012 Croteam Ltd.

#ifndef _EntitiesV_VoiceHolder_INCLUDED
#define _EntitiesV_VoiceHolder_INCLUDED 1
extern "C" DECL_DLL CDLLEntityClass CVoiceHolder_DLLClass;
class CVoiceHolder : public CRationalEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  CTString m_strDescription;
  CTFileName m_fnmMessage;
  BOOL m_bActive;
  INDEX m_ctMaxTrigs;
CAutoPrecacheSound m_aps;
   void Precache(void);
   const CTString & GetDescription(void)const;
#define  STATE_CVoiceHolder_Main 1
  BOOL Main(const CEntityEvent &__eeInput);
  BOOL H0x00e70000_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x00e70001_Main_02(const CEntityEvent &__eeInput);
};
#endif // _EntitiesV_VoiceHolder_INCLUDED
